### ISSUE TITLE
CentOS is not being correctly added to Prey panel.

### ISSUE THREAD

**Issue by lemavri** [prey/prey-node-client#114]
Reported by @netnut404 in #105:

lsb_release -a
LSB Version: :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description: CentOS Linux release 7.0.1406 (Core) 
Release: 7.0.1406
Codename: Core

**Comment by lemavri** [comment]
CentOS is already in the list of supported OSs, but for some reasons is not working. I'm currently running some tests to identify what might be the issue.

**Comment by lemavri** [comment]
I've already identified the issue. This should be fixed early next week.

**Comment by netnut404** [comment]
look forward to seeing that :-)

**Comment by boris** [comment]
Hi @netnut404, this was already deployed to our production environment. Please check if it's working as expected and feel free to reopen this issue (or create a new one) if you find any other issue.
