### ISSUE TITLE
escape emojis when encodeUriCOmponent on geo

### ISSUE THREAD

**Issue by michelson** [prey/prey-node-client#117]
it seems that ssid with emojis are generating errors when the url is encoded:
```
 critical Tue, 07 Apr 2015 16:28:27 GMT UNCAUGHT EXCEPTION: URI malformed
 debug Tue, 07 Apr 2015 16:28:27 GMT URIError: URI malformed
```

the offending line is in geo/index.js 40

 ```javascript 
var str = 'wifi=mac:' + ap.mac_address + '|ssid:' + encodeURIComponent(ap.ssid);
```

I tried to escape the the ssid and it works , but the emoji is removed.

 ```javascript 
var str = 'wifi=mac:' + ap.mac_address + '|ssid:' + encodeURIComponent(escape(ap.ssid));
```

**Comment by tomas** [comment]
What OS? AFAIR we _were_ sanitizing SSID names on `get_access_points_list`.

**Comment by lemavri** [comment]
Here's how to reproduce: 

![screen shot 2015-04-07 at 1 55 19 pm](https://cloud.githubusercontent.com/assets/844344/7028679/c905fcb6-dd2d-11e4-81b1-7a5af8088678.png)

**Comment by lemavri** [comment]
Here's how the airport output looks like:

![screen shot 2015-04-07 at 1 56 41 pm](https://cloud.githubusercontent.com/assets/844344/7028708/fa2fa27e-dd2d-11e4-966e-d79f41af6108.png)

**Comment by lemavri** [comment]
![screen-shot-2015-04-07-at-1 56 41-pm](https://cloud.githubusercontent.com/assets/844344/7029245/b473b6f8-dd32-11e4-9f80-aa7513d9a61f.jpg)

**Comment by lemavri** [comment]
Here's some info on the proposed solution by @michelson 

http://ecmanaut.blogspot.com/2006/07/encoding-decoding-utf8-in-javascript.html

**Comment by tomas** [comment]
We are, indeed, removing weird chars when parsing the output from the system command. Or at least we're trying to:

https://github.com/prey/prey-node-client/blob/master/lib/agent/providers/network/windows.js#L102
https://github.com/prey/prey-node-client/blob/master/lib/agent/providers/network/mac.js#L67
https://github.com/prey/prey-node-client/blob/master/lib/agent/providers/network/linux.js#L107

**Comment by lemavri** [comment]
After some debugging, @tomas found out that what's causing the problem is that the regex is missing the `g` modifier.

**Comment by lemavri** [comment]
According to my testings, this is only reproducible in Mac OS X. Linux and Windows are escaping the emojis correctly.
