### ISSUE TITLE
Cannot add openSUSE device

### ISSUE THREAD

**Issue by johnsto** [prey/prey-node-client#119]
I get this error when trying to authorize:

    Linking device...
    Error! Invalid os:  does not exist.

This is the output of `lsb-release -a`:

    LSB Version:	n/a
    Distributor ID:	openSUSE project
    Description:	openSUSE 20150407 (Tumbleweed) (x86_64)
    Release:	20150407
    Codename:	n/a

Somewhat surprised openSUSE isn't supported already!

**Comment by lemavri** [comment]
We do support openSUSE, but apparently they changed the `Distributor ID` in their recent release. Thanks for your report.

**Comment by lemavri** [comment]
Hello @johnsto, sorry for the delay, we fixed the issue in our servers and it should be working now. Please let us know if the issue persists.

**Comment by andrewrembrandt** [comment]
Hi, this just occurred for me on the most recent openSUSE Tumbleweed update:
````
~> lsb-release -a
LSB Version:    core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0-amd64:desktop-4.0-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch
Distributor ID: openSUSE Tumbleweed
Description:    openSUSE Tumbleweed
Release:        20170529
Codename:       n/a
````
![screenshot_20170618_144949](https://user-images.githubusercontent.com/6534105/27261180-77e72f90-5435-11e7-9bd6-1aed832cd476.png)

Note that the release string is frequently updated

**Comment by javo** [comment]
Hi @andrewrembrandt, The openSUSE is a little complicated, to fix this I need you to make a modification in the client code. You need to go to usr/lib/prey/current/node_modules/linus/index.js, in that file, in the line 54, you have this line of code: cb(null, name.toString().replace(' Linux', ''); I need you to add this: .replace(' Tumbleweed', ''). So, the line should be: cb(null, name.toString().replace(' Linux', '').replace(' Tumbleweed', ''));. Then save the file and run this command to reset the client: sudo pkill -f prx. That should work, please let me know if it's working or not or if you have any doubt.
Regards.
