### ISSUE TITLE
Please Update prey package on NPM!

### ISSUE THREAD

**Issue by faustinoaq** [prey/prey-node-client#120]
I installed prey via npm with: `sudo npm install -g prey` then `prey config gui` and well.

The prey version is **1.3.6**

In the page <https://preyproject.com> says: *You must upgrade Prey to the latest version*

I see <https://www.npmjs.com/package/prey> and the latest prey package is **1.3.6**

I use npm package because .deb not work

**Comment by tomas** [comment]
Thanks for the heads up. Will take a look at this right away.

**Comment by tomas** [comment]
Ok mister. Just pushed the missing versions to npm (1.3.7, 1.3.8 and 1.3.9). Thanks again for the reminder.

**Comment by faustinoaq** [comment]
Thanks @tomas by the response

**Comment by peterhoeg** [comment]
@tomas, the version available via npm (1.3.9) is far out of date again.

**Comment by raliste** [comment]
@peterhoeg we will be updating the updated versions (1.5.0 and 1.5.1) early next week.
