### ISSUE TITLE
[OS X 10.6.8] Config won't open: missing module argparse

### ISSUE THREAD

**Issue by cpcallen** [prey/prey-node-client#125]
I had 0.6.4 installed, and, thinking it was very out-of-date removed it using the uninstaller from 0.5.3; this cleanly removed the crontab entry and /usr/share/prey/ as expected.

I then downloaded prey-mac-1.3.9-x64.pkg and installed it; installation completed successfully.  I was expecting to be prompted for login credentials, but nothing happened.  After a bit of googling for possible solutions, I tried starting the config GUI manually:

```
$ cd /usr/lib/prey/current
$ bin/prey config gui
Error! Oops. Seems you don't have write permissions. Try running with sudo.

$ sudo bin/prey config gui
Password:
Firing up config GUI!

$ echo $?
0
```

The symptoms are the same as [issue 63](https://github.com/prey/prey-node-client/issues/63), but the cause appears to be quite different:

```
$ python --version
Python 2.7.3

$ lib/conf/gui/linux/prey-config.py    # not sure why I expected this to work...
Traceback (most recent call last):
  File "lib/conf/gui/linux/prey-config.py", line 19, in <module>
    import pygtk
ImportError: No module named pygtk

$ lib/conf/gui/mac/PreyConfig.app/Contents/MacOS/PreyConfig 
Traceback (most recent call last):
  File "lib/conf/gui/mac/PreyConfig.app/Contents/MacOS/prey-config.py", line 14, in <module>
    import argparse
ImportError: No module named argparse
```

I was able to configure it manually:
```
$ sudo bin/prey config account setup

Do you already have a Prey account? 
 - yes/no: [yes] yes
Well hello old friend!
Please type your account's email address. 
 - email: [redacted]
Well played. Now enter your password. 
 - pass: ********
Credentials verified.
Linking device...
Voila! All good.
```

... but figuring out how to do so was not super-easy, and I suspect a typical user wouldn't even realise that something had gone wrong.

**Comment by lemavri** [comment]
Hello @cpcallen, thanks for your report. It's good to know you were finally able to configure it. I'll go ahead and modify the title of the issue to make it more to the point.
