### ISSUE TITLE
Prey client doesn't report neighboring WiFi signal strength or network security

### ISSUE THREAD

**Issue by fanuneza** [prey/prey-node-client#135]
## Problem

This is how reports look on Prey for laptops.

![screenshot 2015-05-20 16 27 05](https://cloud.githubusercontent.com/assets/401279/7734635/e31c7ae2-ff0d-11e4-8dd9-7bd97770154d.png)

And this is how they look for Android devices.

![screenshot 2015-05-20 16 27 27](https://cloud.githubusercontent.com/assets/401279/7734638/e8970b40-ff0d-11e4-9596-9aa89d6d10df.png)

Information should be the same for both.

## How it was detected

Customer feedback.

## Suggestion

Fix, fix, fix <3

## Resources

- https://secure.helpscout.net/conversation/92192848/21770/

**Comment by boris** [comment]
I'm not able to reproduce this issue:

![screen shot 2015-05-22 at 9 59 20](https://cloud.githubusercontent.com/assets/537305/7770900/7592797e-0069-11e5-8367-fdb8410d596b.png)

Could you please provide more information about the device?

**Comment by lemavri** [comment]
I wasn't able either. Yesterday I got a report with all the Wi-Fi signals in it.

**Comment by fanuneza** [comment]
64-bits Windows 8.1 laptop running Prey 1.3.9. Just replicated the issue.

**Comment by lemavri** [comment]
@fanuneza what's the output of running `netsh wlan show all` ?

**Comment by fanuneza** [comment]
@lemavri: I'm sending you that privately. Everything looks fine, though.

**Comment by lemavri** [comment]
@fanuneza could you please try to reproduce with 1.4.0 or 1.4.1pre?
