### ISSUE TITLE
Prey unconfigures after every system update (Elementary OS)

### ISSUE THREAD

**Issue by beeatriz** [prey/prey-node-client#136]
## Problem

User has to manually launch GUI after Prey installation and every system update on Elementary OS. Gets following output after everytime he installs or updates Prey:

https://gist.githubusercontent.com/beeatriz/a5c49a13ce2f2ccaf2a3/raw/gistfile1.txt

## How it was detected.

User feedback

## Suggestion

Check for bugs and solve

## References

https://secure.helpscout.net/conversation/93413306/22180/

**Comment by lemavri** [comment]
I've contacted the user to help him with his particular problem. The more general issue is referenced in #138.
