### ISSUE TITLE
Unable to install prey on debian Wheezy

### ISSUE THREAD

**Issue by FilipoMoake** [prey/prey-node-client#141]
Hello !

The install : 
Prey package : prey_1.3.10_amd64.deb
Debian : Wheezy 7.8
Kernel : 3.2.0-4-amd64 (#1 SMP Debian 3.2.68-1+deb7u2)
Gnome : 3.4
----------------
Installed with GDebi :
Result : 

---------------
GDebi prey_1.3.10_amd64.deb

*e_modules to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/serve-static to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/buckle/node_modules/decompress-zip to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/duplexer2/node_modules/readable-stream/node_modules/core-util-is/lib to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/duplexer2/node_modules/readable-stream/node_modules/isarray/build to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/through2/node_modules/readable-stream/node_modules/core-util-is/lib to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/through2/node_modules/readable-stream/node_modules/isarray/build to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/rimraf/node_modules/glob to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/buckle/node_modules to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/duplexer2/node_modules/readable-stream/node_modules/core-util-is to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/duplexer2/node_modules/readable-stream/node_modules/isarray to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/through2/node_modules/readable-stream/node_modules/core-util-is to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/through2/node_modules/readable-stream/node_modules/isarray to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/rimraf/node_modules to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/buckle to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/duplexer2/node_modules/readable-stream/node_modules to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/through2/node_modules/readable-stream/node_modules to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/rimraf to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/duplexer2/node_modules/readable-stream to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/through2/node_modules/readable-stream to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/duplexer2/node_modules to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/through2/node_modules to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/duplexer2 to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules/through2 to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest/node_modules to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules/hyperquest to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail/node_modules to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules/buildmail to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer/node_modules to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules/nodemailer to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10/node_modules to uid 997 and gid 997
chowning /usr/lib/prey/versions/1.3.10 to uid 997 and gid 997
chowning /usr/lib/prey/versions to uid 997 and gid 997
chowning /usr/lib/prey to uid 997 and gid 997
Setting permissions on /etc/prey
chowning /etc/prey to uid 997 and gid 997
Setting permissions on /var/log/prey.log
chowning /var/log/prey.log to uid 997 and gid 997
Running "config activate" as prey
--
Ensuring presence of config dir: /etc/prey
Syncing /etc/prey/prey.conf with /usr/lib/prey/versions/1.3.10/prey.conf.default
Setting up this as current...
No version is set as current.
Setting permissions on /usr/lib/prey/current
Running post_activate hooks...
Voila! All good.
--
Installing init scripts.
Error! Command failed: /bin/sh: 1: /etc/init.d/prey-agent: Permission denied

dpkg: erreur de traitement de prey (--install) :
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1
Des erreurs ont été rencontrées pendant l'exécution :
 prey*

-----------------

**Then if i edit the properties of /etc/init.d/prey-agent file, i see that it is not set as "launchable", so i change this status to on.**

**Then i reinstall the prey deb with GDebi, and now it goes a little bit further, and GDeb ifinish with this error message :**

------------------
Enable to launch bin/prey config gui as a prey user
Can't communicate with gksu-run-helper
Expected : gksu:waiting
------------------

I can launch "/usr/bin/prey/current/bin/sh prey config" and connect to my account.

Then if launch "/usr/bin/prey/current/bin/sh prey -D" it display : 

-------------------

  PREY 1.3.10 spreads its wings!
  Current time: Thu Jul 09 2015 16:06:58 GMT+1100 (NCT)
  Running with PID 7840 as root over Node.js v0.10.36 on a x64 linux system (3.2.0-4-amd64)

    debug Thu, 09 Jul 2015 05:06:58 GMT [updater] Checking for updates on stable branch...
   notice Thu, 09 Jul 2015 05:06:59 GMT [updater] New version found: 1.3.9
     warn Thu, 09 Jul 2015 05:06:59 GMT [updater] Starting upgrade process. Hold on tight!
     info Thu, 09 Jul 2015 05:07:00 GMT [updater] Error! v1.3.9 already installed in /usr/lib/prey/versions
     info Thu, 09 Jul 2015 05:07:00 GMT [triggers] Watching: connection, network, power
     info Thu, 09 Jul 2015 05:07:00 GMT [actions] Starting trigger: connection
     info Thu, 09 Jul 2015 05:07:00 GMT [actions] Running: connection
     info Thu, 09 Jul 2015 05:07:00 GMT [actions] Starting trigger: network
     info Thu, 09 Jul 2015 05:07:00 GMT [actions] Starting trigger: power
     info Thu, 09 Jul 2015 05:07:00 GMT [actions] Running: network
     info Thu, 09 Jul 2015 05:07:00 GMT [actions] Running: power
    debug Thu, 09 Jul 2015 05:07:01 GMT [providers] Fetching active_access_point_name
    debug Thu, 09 Jul 2015 05:07:01 GMT [providers] Fetching private_ip
    debug Thu, 09 Jul 2015 05:07:01 GMT [hooks] Hook triggered: connected
    debug Thu, 09 Jul 2015 05:07:01 GMT [control-panel] Sending GET request #1 to https://solid.preyproject.com
   notice Thu, 09 Jul 2015 05:07:01 GMT [control-panel] Checking for existing port mappings...
     info Thu, 09 Jul 2015 05:07:01 GMT Plugin loaded: control-panel
     info Thu, 09 Jul 2015 05:07:01 GMT 1 plugins loaded with 0 errors.
     info Thu, 09 Jul 2015 05:07:01 GMT Initialized.
     info Thu, 09 Jul 2015 05:07:01 GMT [control-panel] No previously mapped ports found.
     info Thu, 09 Jul 2015 05:07:01 GMT [control-panel] Attempting to map external port 30333
    debug Thu, 09 Jul 2015 05:07:02 GMT [control-panel] Attempt #1 took 1.309 seconds.
    debug Thu, 09 Jul 2015 05:07:02 GMT [control-panel] Syncing settings.
   notice Thu, 09 Jul 2015 05:07:02 GMT [control-panel] Updating value of auto_connect to true
    debug Thu, 09 Jul 2015 05:07:04 GMT [control-panel] Fetching instructions...
    debug Thu, 09 Jul 2015 05:07:04 GMT [control-panel] Sending GET request #1 to https://solid.preyproject.com
    debug Thu, 09 Jul 2015 05:07:05 GMT [control-panel] Attempt #1 took 1.236 seconds.
    debug Thu, 09 Jul 2015 05:07:05 GMT [control-panel] Re-scheduling request.
 critical Thu, 09 Jul 2015 05:07:06 GMT UNCAUGHT EXCEPTION: Missing keys.
    debug Thu, 09 Jul 2015 05:07:06 GMT
     info Thu, 09 Jul 2015 05:07:11 GMT Gracefully shutting down. Will self-destruct in 5 secs.
    debug Thu, 09 Jul 2015 05:07:11 GMT Unloading plugins.
    debug Thu, 09 Jul 2015 05:07:11 GMT Unloading control-panel plugin...
    debug Thu, 09 Jul 2015 05:07:11 GMT Plugin unloaded: control-panel
    debug Thu, 09 Jul 2015 05:07:11 GMT Stopping actions.
     info Thu, 09 Jul 2015 05:07:11 GMT [actions] Stopping: connection
     info Thu, 09 Jul 2015 05:07:11 GMT [actions] Stopping: network
     info Thu, 09 Jul 2015 05:07:11 GMT [actions] Stopping: power
    debug Thu, 09 Jul 2015 05:07:11 GMT Unloading hooks.
     info Thu, 09 Jul 2015 05:07:11 GMT [hooks] Unregistering hooks.
    debug Thu, 09 Jul 2015 05:07:11 GMT Canceling reports.
    debug Thu, 09 Jul 2015 05:07:11 GMT Unwatching triggers.
    debug Thu, 09 Jul 2015 05:07:11 GMT Cleaning up temporary files.
     info Thu, 09 Jul 2015 05:07:11 GMT Shutdown complete. Have a jolly good day sir.

---------------

STRANGE !? : 

1. it appears that in folder /usr/bin/prey/versions, there's 2 differents versions folders : 1.3.9 and 1.3.10.

2. it says that 1.3.9 is the newest version

3. If i launch "sh /etc/initd.d/prey-agent" it works but only for a few seconds. If i launch prey-agent status just after, the result is good. If i relaunch prey-agent status after maybe 10 seconds, no more prey-agent running. It looks like something killed the process.

4. For information, there's nothing about prey in the cron/crontab folders 

------------------

Any idea how to solve this and have a working install ?

Thank you in advance,

Regards,

**Comment by lemavri** [comment]
Hello @FilipoMoake, thanks for your feedback :).

1 and 2 are expected. We launched 1.3.10 but a bug in the way we were comparing versions wrongly considered 1.3.9 to be higher than 1.3.10, so we did a rollback and set 1.3.9 as the latest version again. I'm working on the new release that will fix that and a few other issues.

3. I'm seeing this `UNCAUGHT EXCEPTION: Missing keys.` in your log file. Maybe this is what's killing the agent. I'll have to look further into that as soon as I have the chance.

4. That is good, we no longer use cron for scheduling requests to our servers, the client takes care of that as long as it's alive, which is not happening in your case by point 3.

**Comment by FilipoMoake** [comment]
Thank you lemavri.
Waiting for news from you.
Regards.

**Comment by fanuneza** [comment]
Hi @FilipoMoake,

I remember that Gdebi had trouble with the installer in the past. Does DPKG also get you errors while installing the package?

The instruction is `dpkg -i prey_1.3.10_amd64.deb`, just in case. You might have to install dependencies after that, and probably an `apt-get install -f` will do the trick. You need root permissions for both commands.

I'm not sure if that will work but I'd give it a try :)

**Comment by FilipoMoake** [comment]
Hi Iemavri,

Thank you for your message,

I've just tried what you suggested. Unsuccessful too.

Here is the end message from apt-get install -f : 

Ensuring presence of config dir: /etc/prey
Syncing /etc/prey/prey.conf with /usr/lib/prey/versions/1.3.10/prey.conf.default
Setting up this as current...
Warning: This version is already set as current.
Setting permissions on /usr/lib/prey/current
Running post_activate hooks...
Voila! All good.
--
Installing init scripts.
Error! Command failed: /bin/sh: 1: /etc/init.d/prey-agent: Permission denied

dpkg: erreur de traitement de prey (--configure) :
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1
Des erreurs ont été rencontrées pendant l'exécution :
 prey
Creating index of upgradeable packages ...
E: Sub-process /usr/bin/dpkg returned an error code (1)
---------

Regards

**Comment by FilipoMoake** [comment]
A few more news ...
I was able to go to the end of the install process with that : 
. # dpkg -i prey_1.3.10_amd64.deb (end with Error! Command failed: /bin/sh: 1: /etc/init.d/prey-agent: Permission denied)
. i manually change /etc/init.d/prey-agent file as "launchable" that was missing
. i modify the script /var/lib/dpkg/info/prey.postinst - line 74 : 
         before :       env DISPLAY=:0.0 gksu -u $PREY_USER "$PREY_BIN config gui"
         after    :       sudo -u prey /usr/lib/prey/current/bin/prey config gui
         (for info, it was unsuccessful with : sudo -u  $PREY_USER "$PREY_BIN config gui") 
. then i run # apt-get install -f
. and finally the script "prey config gui" is launched and the install process end successfully.

But, prey still not refreshing the status in the account, and so finally prey is not working ...

Hope it helps a little bit ...
