### ISSUE TITLE
Ubuntu (gksu:26715): Gtk-WARNING **: cannot open display: :0.0

### ISSUE THREAD

**Issue by binarykitchen** [prey/prey-node-client#153]
I tried to install this deb file on Ubuntu 15.40
https://prey-releases.s3.amazonaws.com/node-client/1.4.1/prey_1.4.1_amd64.deb

But at the very end it crashed due to a gksu bug:

```
...
chowning /usr/lib/prey/versions/1.4.1/node_modules/nodemailer/node_modules/buildmail to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.4.1/node_modules/nodemailer/node_modules to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.4.1/node_modules/nodemailer to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.4.1/node_modules to uid 999 and gid 999
chowning /usr/lib/prey/versions/1.4.1 to uid 999 and gid 999
chowning /usr/lib/prey/versions to uid 999 and gid 999
chowning /usr/lib/prey to uid 999 and gid 999
Setting permissions on /etc/prey
chowning /etc/prey/prey.conf to uid 999 and gid 999
chowning /etc/prey to uid 999 and gid 999
Setting permissions on /var/log/prey.log
chowning /var/log/prey.log to uid 999 and gid 999
Running "config activate" as prey
--
Ensuring presence of config dir: /etc/prey
Syncing /etc/prey/prey.conf with /usr/lib/prey/versions/1.4.1/prey.conf.default
Setting up this as current...
No version is set as current.
Setting permissions on /usr/lib/prey/current
Running post_activate hooks...
Voila! All good.
--
Installing init scripts.
Sweet! Please run `prey config gui` to finish installation.
Voila! All good.
No protocol specified

(gksu:26715): Gtk-WARNING **: cannot open display: :0.0
dpkg: error processing package prey (--install):
 subprocess installed post-installation script returned error exit status 1
```

**Comment by miltonlaufer** [comment]
Same problem here, ubuntu 14.04

**Comment by muranyia** [comment]
Same here, Ubuntu 14.04.3 amd64

**Comment by muranyia** [comment]
Another part of the problem is that it leaves the Ubuntu software installer in a state that every day it tries to finish the installation of Prey and then fails.

Interestingly, Prey does not appear in the list of Software Updates, the failure happens at the end of the update process though.

**Comment by beniwtv** [comment]
Same problem on SteamOS.
In SteamOS, the "DISPLAY" environment variable is "DISPLAY=:1".

However, the error mentions :0.0, so Prey does not appear to honor the env variable, but rather it seems hard-coded.

**Comment by ylot0** [comment]
gksu:4708): Gtk-WARNING **: cannot open display: :0.0
dpkg: error processing package prey (--install):
subprocess installed post-installation script returned error exit status 1

**Comment by derekyerger** [comment]
To get rid of the repeat attempt to configure prey every time packages are installed/upgraded, edit the file `/var/lib/dpkg/info/prey.postinst` by remarking the following line:
```
 74       env DISPLAY=:0.0 gksu -u $PREY_USER "$PREY_BIN config gui"
```
Additionally, as stated above, the configuration script can be run from a normal (non-elevated) prompt.
