### ISSUE TITLE
Invalid os:  does not exist

### ISSUE THREAD

**Issue by rebeccaadams1232** [prey/prey-node-client#155]
Hi, I'm having the same issue as here: https://github.com/prey/prey-node-client/issues/45 which is closed
Perhaps Redhat Workstation isn't recognised?

lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseWorkstation
Description:	Red Hat Enterprise Linux Workstation release 6.6 (Santiago)
Release:	6.6
Codename:	Santiago

====================
Output from /usr/lib/node_modules/prey/bin/prey

  PREY 1.3.9 spreads its wings!
  Current time: Wed Sep 09 2015 14:45:00 GMT+0100 (BST)
  Running with PID 3592 as root over Node.js v0.10.40 on a x64 linux system (2.6.32-504.23.4.el6.x86_64)

     info Wed, 09 Sep 2015 13:45:00 GMT [triggers] Watching: connection, network, power
     info Wed, 09 Sep 2015 13:45:00 GMT [actions] Starting trigger: connection
     info Wed, 09 Sep 2015 13:45:00 GMT [actions] Running: connection
     info Wed, 09 Sep 2015 13:45:00 GMT [actions] Starting trigger: network
     info Wed, 09 Sep 2015 13:45:00 GMT [actions] Starting trigger: power
     info Wed, 09 Sep 2015 13:45:00 GMT [actions] Running: network
     info Wed, 09 Sep 2015 13:45:00 GMT [actions] Running: power
     info Wed, 09 Sep 2015 13:45:00 GMT [control-panel] Gathering device data...
     info Wed, 09 Sep 2015 13:45:00 GMT [reports] Gathering specs report.
    error Wed, 09 Sep 2015 13:45:00 GMT [reports] Unable to get storage_devices_list: TODO!
     info Wed, 09 Sep 2015 13:45:00 GMT [reports] Report gathered: specs
    error Wed, 09 Sep 2015 13:45:01 GMT [control-panel] Unable to register device: Invalid os:  does not exist.
    error Wed, 09 Sep 2015 13:45:01 GMT Error: Invalid os:  does not exist.
     info Wed, 09 Sep 2015 13:45:01 GMT 1 plugins loaded with 1 errors.
 critical Wed, 09 Sep 2015 13:45:01 GMT UNCAUGHT EXCEPTION: Invalid os:  does not exist.
     info Wed, 09 Sep 2015 13:45:01 GMT Gracefully shutting down. Will self-destruct in 5 secs.
     info Wed, 09 Sep 2015 13:45:01 GMT [actions] Stopping: connection
     info Wed, 09 Sep 2015 13:45:01 GMT [actions] Stopping: network
     info Wed, 09 Sep 2015 13:45:01 GMT [actions] Stopping: power
     info Wed, 09 Sep 2015 13:45:01 GMT [hooks] Unregistering hooks.
     info Wed, 09 Sep 2015 13:45:06 GMT Time's up, shutdown forced. Have a jolly good day sir.

**Comment by lemavri** [comment]
Hello @rebeccaadams1232,

I'll take care of adding said OS to the valid OS list in our servers and let you know when it's done.

**Comment by rebeccaadams1232** [comment]
Many thanks :)

**Comment by lemavri** [comment]
@rebeccaadams1232 

We just deployed the fix with the OS addition. Please, feel free to check if it's working now and let us know how it goes. In the meanwhile I'll go ahead and mark the issue as close, but you can re-open it at any time.

**Comment by rebeccaadams1232** [comment]
Wahoo, works now :)
Thanks!

**Comment by lemavri** [comment]
I'm glad it's working now. Thanks for letting us know.

**Comment by explitit** [comment]
Hello guys. we have a big trouble to install prey on Sailfish OS Version 2.0.2.48 (i486 / armv7l)

Early versions of Sailfish OS were supported on the Jolla phone.
No we get the same 
Error! Invalid os:   does not exist.

Which information do you need to support the newer versions of sailfish OS?

**Comment by explitit** [comment]
Do you already have a Prey account?
- yes/no: [yes]
Well hello old friend!
Please type your account's email address.
- email: ex****@*****.***
Well played. Now enter your password.
- pass: ***********
Credentials verified.
Linking device...
Error! Invalid os:  does not exist.

[root@localhost nemo]# lsb_release -a
LSB Version:    :core-3.1-arm:core-3.1-noarch:core-3.2-arm:core-3.2-noarch:core-4.0-arm:core-4.0-noarch:desktop-3.1-arm:desktop
-3.1-noarch:desktop-3.2-arm:desktop-3.2-noarch:desktop-4.0-arm:desktop-4.0-noarch
Distributor ID: #Thisfileiscopiedashw-release(analogoustoos-release)
Description:    # This file is copied as hw-release (analogous to os-release)
Release:        n/a
Codename:       analogoustoos-release
[root@localhost nemo]#

**Comment by explitit** [comment]
[root@Sailfish nemo]# lsb_release -a
LSB Version:    :core-3.1-ia32:core-3.1-noarch:core-3.2-ia32:core-3.2-noarch:core-4.0-ia32:core-4.0-noarch:desktop-3.1-ia32:des
ktop-3.1-noarch:desktop-3.2-ia32:desktop-3.2-noarch:desktop-4.0-ia32:desktop-4.0-noarch
Distributor ID: #Thisfileiscopiedashw-release(analogoustoos-release)
Description:    # This file is copied as hw-release (analogous to os-release)
Release:        n/a
Codename:       analogoustoos-release
[root@Sailfish nemo]#


This is for the i486 (Tablet), the upper lsb_release is arm

**Comment by Grigsby2** [comment]
I have the same problem on openSUSE Leap 42.1 (which is not really an obscure distribution).

Prey output:

  PREY 1.3.9 spreads its wings!
  Current time: Fri Aug 12 2016 22:47:07 GMT-0400 (EDT)
  Running with PID 18298 as root over Node.js v4.4.5 on a x64 linux system (4.1.27-27-default)

     info Sat, 13 Aug 2016 02:47:07 GMT [triggers] Watching: connection, network, power
     info Sat, 13 Aug 2016 02:47:07 GMT [actions] Starting trigger: connection
     info Sat, 13 Aug 2016 02:47:07 GMT [actions] Running: connection
     info Sat, 13 Aug 2016 02:47:07 GMT [actions] Starting trigger: network
     info Sat, 13 Aug 2016 02:47:07 GMT [actions] Starting trigger: power
     info Sat, 13 Aug 2016 02:47:07 GMT [actions] Failed: network -> ENOENT - Command not found: /usr/bin/dbus-monitor
    error Sat, 13 Aug 2016 02:47:07 GMT Error: ENOENT - Command not found: /usr/bin/dbus-monitor
     info Sat, 13 Aug 2016 02:47:07 GMT [actions] Failed: power -> ENOENT - Command not found: /usr/bin/dbus-monitor
    error Sat, 13 Aug 2016 02:47:07 GMT Error: ENOENT - Command not found: /usr/bin/dbus-monitor
     info Sat, 13 Aug 2016 02:47:07 GMT [control-panel] Gathering device data...
     info Sat, 13 Aug 2016 02:47:07 GMT [reports] Gathering specs report.
    error Sat, 13 Aug 2016 02:47:07 GMT [reports] Unable to get storage_devices_list: TODO!
     info Sat, 13 Aug 2016 02:47:07 GMT [reports] Report gathered: specs
    error Sat, 13 Aug 2016 02:47:08 GMT [control-panel] Unable to register device: Invalid os:  does not exist.
    error Sat, 13 Aug 2016 02:47:08 GMT Error: Invalid os:  does not exist.
     info Sat, 13 Aug 2016 02:47:08 GMT 1 plugins loaded with 1 errors.
 critical Sat, 13 Aug 2016 02:47:08 GMT UNCAUGHT **EXCEPTION: Invalid os:  does not exist.**
     info Sat, 13 Aug 2016 02:47:08 GMT Gracefully shutting down. Will self-destruct in 5 secs.
     info Sat, 13 Aug 2016 02:47:08 GMT [actions] Stopping: connection
     info Sat, 13 Aug 2016 02:47:08 GMT [hooks] Unregistering hooks.
     info Sat, 13 Aug 2016 02:47:13 GMT Time's up, shutdown forced. Have a jolly good day sir.

lsb_release -a output:

LSB Version: core-5.0-amd64:core-5.0-noarch:desktop-5.0-amd64:desktop-5.0-noarch:imaging-5.0-amd64:imaging-5.0-noarch:languages-5.0-amd64:languages-5.0-noarch
Distributor ID: SUSE LINUX
Description: openSUSE Leap 42.1 (x86_64)
Release: 42.1
Codename: n/a


Any help or advice would be appreciated.

**Comment by explitit** [comment]
Someone from prey need to update the program to recognize our distros. without help from prey, that would be difficult.... :-(
