### ISSUE TITLE
Add Prey binary to Linux path

### ISSUE THREAD

**Issue by mhalano** [prey/prey-node-client#159]
Probably would be a good idea if prey command is in Linux path. I think is possible add into .deb packages a symlink on /usr/bin to /usr/lib/prey/current/bin/prey.

**Comment by luzfcb** [comment]
same problem here

**Comment by muranyia** [comment]
Same here

`
$ prey config gui
No command 'prey' found
`

**Comment by camilaburgos** [comment]
Hi, @mhalano, @luzfcb and @muranyia. Are you still having this problem?

**Comment by mhalano** [comment]
@camilaburgos Version 1.6.1 still don't have the symlink inside /usr/bin.

**Comment by mhalano** [comment]
@camilaburgos Just installed 1.6.6 and confirmed by command 'whereis prey'

**Comment by breversa** [comment]
Same issue with version 1.9.9 as of today.

**Comment by mhalano** [comment]
@patriciojofre There is a commit or an explanation why this issue was closed?

**Comment by mhalano** [comment]
Any news why this issue is closed without a proper solution?
