### ISSUE TITLE
El Capitan upgrade disables Prey 1.4.2

### ISSUE THREAD

**Issue by MacksMind** [prey/prey-node-client#160]
Prey 1.4.2 auto updated before the El Capitan upgrade. After the upgrade prey stopped working, but reinstall of 1.4.2 fixed it. It looks like the installer puts prey in /usr/local/lib, but the autoupdate doesn't move it there from /usr/lib/prey.

**Comment by paxperscientiam** [comment]
Hi MacksMind, I to am having trouble with prey on El Capitan. After upgrading the OS, I noticed from Console logs that the prey agent was crashing and restarting, essentially, continuously. At the time I was running the original, non-node, version. I decided then to uninstall it and give the new node version a try. Still, not working.

Was there anything else you had to do to get your installation working? By the way, I installed via NPM.

**Comment by MacksMind** [comment]
I did nothing except install a fresh download of 1.4.2 over top of the existing install.
