### ISSUE TITLE
prey doesn't recognise sabayon linux

### ISSUE THREAD

**Issue by parapente** [prey/prey-node-client#163]
I tried to setup prey and I get using both the gui and cli version of prey config the message:
"Error! Invalid os:  does not exist."

I installed prey using npm. If you need any extra info plese feel free to ask.

**Comment by lemavri** [comment]
Hello @parapente, thanks for your report. I will let you know as soon as this is resolved.

**Comment by lemavri** [comment]
@parapente, could you please run `lsb-release -a` in your Terminal and paste the output here? Thanks in advance.

**Comment by parapente** [comment]
$ lsb_release -a
LSB Version:    n/a
Distributor ID: Sabayon
Description:    Sabayon Linux amd64 15.11
Release:        n/a
Codename:       n/a

Hope this helps!
