### ISSUE TITLE
"Unable to map port: Could not locate gateway on time."

### ISSUE THREAD

**Issue by paxperscientiam** [prey/prey-node-client#168]
After giving up on prey installed via NPM, I decided to try directly from the website.

Whereas the prey agent would crash and restart continuously when it had been installed via NPM, this is no longer the case. However, prey is still not working.

[log.txt](https://github.com/prey/prey-node-client/files/32344/log.txt)

Any thoughts on how to remedy this?

**Comment by lemavri** [comment]
Hello. According to the log, it should be working. The "could not locate gateway on time" part is because Prey was unable to use uPnP, most likely because your router does not support it. Nevertheless, uPnP has been removed in the release soon to be uploaded.

Could you please check if your config file located in `/etc/prey/prey.log` contains an API and Device keys? (Do not share your keys here if that's the case).

**Comment by paxperscientiam** [comment]
Hiya,

Hm okay. Did you mean `/etc/prey/prey.conf`? I have that and it does indeed have a device key and an API key.

**Comment by lemavri** [comment]
Yes, sorry, that's what I meant. Did you try sending instructions (alert, alarm) to your device from the Prey website?

**Comment by paxperscientiam** [comment]
I've only tried the location service. Let me give that a whirl. BRB

**Comment by lemavri** [comment]
What OS do you have? I could provide you with a beta version of the next release which should be more responsive to instructions from our servers.

**Comment by paxperscientiam** [comment]
If you're interested, I have a hunch why their might be a problem with NPM installed version working. I installed NPM via Macports and as such my global modules require sudo to update. But that's just a guess.

**Comment by lemavri** [comment]
To be honest, the NPM version is not very reliable right now and the stand-alone version is recommended (which I see you installed it, though).

**Comment by lemavri** [comment]
> Yeah, should have checked the volume on my head phones first
Woops. I'm sorry again, I forgot to warn you about that. I learnt the hard way to remove my headphones prior to running any test 🙄.

**Comment by paxperscientiam** [comment]
OK, after some digging, I'm noticing a few potential minor issues.

When device location is requested from the online Control Panel by either clicking the "Update Location" button or by refreshing the webpage, the "last seen" response fails to update even though the Control Panel reports "device reached" and "got location." That said, sometimes those responses are followed by a failure to locate response.

Looking over the log file, it seems that both alert and alarm "actions" are recorded. However, there is no record of attempts to locate the device in the log. Perhaps this is by design? I'm left wondering if the mother ship is truly determining the location of my machine.

**Comment by lemavri** [comment]
Until version 1.4.2 the Prey client was connecting to our servers via intervals. Starting from the next release (most likely we'll make the jump to 1.5.0), Prey will use a completely different approach to the way it connects to our servers, which solves the delayed location issue you mention and a few other user experience related problems, also allowing for responsive and stable behaviour.

**Comment by paxperscientiam** [comment]
Ah, thanks for the explanation,  lemavri.
