### ISSUE TITLE
Error trying to execute "prey config [gui]"

### ISSUE THREAD

**Issue by WolfangAukang** [prey/prey-node-client#169]
Hello, I have an issue trying to execute prey on Fedora 22. Following the instructions on README.md, it says to execute after the installation through npm the command "prey config [gui]". Although, I received the following error:

[pedro@eyjafjallajokull bin]$ prey config

module.js:340
    throw err;
          ^
Error: Cannot find module '/usr/bin/lib/node_modules/prey/lib/conf/cli.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
 
I found a solution from a similar closed issue. One of the users indicated that running "node /lib/node_modules/prey/lib/conf/cli.js config gui" (in my case I had to sudo it, because of the writing permissions) has worked for him. I tried the same and it showed the GUI and I could install it fine.

 So, maybe the script is looking for the wrong path.

**Comment by aairey** [comment]
Same on Fedora 23.

@WolfangAukang: thanks for providing the workaround.

**Comment by errollgarner** [comment]
Same issue in Fedora 21 and the same fix also works.
Thanks @WolfangAukang !
