### ISSUE TITLE
Linux 15.04 no hardware information showed

### ISSUE THREAD

**Issue by leeyuentuen** [prey/prey-node-client#178]
Logfile

```
  ████████████████ ████████████████ ████████████████ ██            ██
  ██            ██ ██               ██            ██ ██            ██
  ██            ██ ██               ████████████████ ██            ██
  ██            ██ ██               ██               ██            ██
  ████████████████ ██               ████████████████ ████████████████
  ██                                                               ██
  ██                                                 ████████████████

  PREY 1.4.2 spreads its wings!
  Current time: Fri Dec 18 2015 11:13:19 GMT+0100 (CET)
  Running with PID 14023 as prey over Node.js v0.10.36 on a x64 linux system (4.1.6-040106-generic)

     info Fri, 18 Dec 2015 10:13:20 GMT [triggers] Watching: connection, network, power
     info Fri, 18 Dec 2015 10:13:20 GMT [actions] Starting trigger: connection
     info Fri, 18 Dec 2015 10:13:20 GMT [actions] Running: connection
     info Fri, 18 Dec 2015 10:13:20 GMT [actions] Starting trigger: network
     info Fri, 18 Dec 2015 10:13:20 GMT [actions] Starting trigger: power
    error Fri, 18 Dec 2015 10:13:20 GMT Error: Cannot find module './linux'
    error Fri, 18 Dec 2015 10:13:20 GMT Error: Cannot find module './linux'
     info Fri, 18 Dec 2015 10:13:20 GMT [actions] Running: network
     info Fri, 18 Dec 2015 10:13:20 GMT [actions] Running: power
   notice Fri, 18 Dec 2015 10:13:20 GMT [control-panel] Checking for existing port mappings...
     info Fri, 18 Dec 2015 10:13:20 GMT Plugin loaded: control-panel
     info Fri, 18 Dec 2015 10:13:20 GMT 1 plugins loaded with 0 errors.
     info Fri, 18 Dec 2015 10:13:20 GMT Initialized.
   notice Fri, 18 Dec 2015 10:13:20 GMT [control-panel] Updating value of auto_connect to true
   notice Fri, 18 Dec 2015 10:13:20 GMT [control-panel] Updating value of scan_hardware to true
     info Fri, 18 Dec 2015 10:13:20 GMT [reports] Gathering specs report.
    error Fri, 18 Dec 2015 10:13:20 GMT [reports] Unable to get storage_devices_list: TODO!
     info Fri, 18 Dec 2015 10:13:20 GMT [reports] Report gathered: specs
     info Fri, 18 Dec 2015 10:13:20 GMT [reports] Gathering status report.
     info Fri, 18 Dec 2015 10:13:25 GMT [control-panel] No previously mapped ports found.
     info Fri, 18 Dec 2015 10:13:25 GMT [control-panel] Attempting to map external port 30332
     info Fri, 18 Dec 2015 10:13:33 GMT [reports] Report gathered: status
     info Fri, 18 Dec 2015 10:13:33 GMT [control-panel] Posting data
     info Fri, 18 Dec 2015 10:13:33 GMT [control-panel] Got 200 response: OK
    error Fri, 18 Dec 2015 10:14:01 GMT [control-panel] Unable to map port: Could not locate gateway on time.
     info Fri, 18 Dec 2015 10:14:01 GMT [control-panel] Queuing check-ins every 0.5 minutes.
```

see screenshot as results
good one in windows
![prey_ok](https://cloud.githubusercontent.com/assets/1487966/11894781/c9d26ff2-a579-11e5-9089-184cf9e3b7b8.png)
bad one in linux, there is no service tag for our laptop
![prey_bad](https://cloud.githubusercontent.com/assets/1487966/11894784/cbaabca8-a579-11e5-9d51-1ea4be1bdbcb.png)

**Comment by renanmarks** [comment]
Same problem, but even worse: only gets cpu info.

![prey](https://cloud.githubusercontent.com/assets/273643/12218022/dd0c73aa-b6f0-11e5-9653-a22de5fa514f.png)

**Comment by camilaburgos** [comment]
Hello, @leeyuentuen, @renanmarks. Are you still having this problem?

**Comment by renanmarks** [comment]
Hi @camilaburgos, yes it is still present. :(

Since last post (on 9/jan) I've upgraded and reinstalled all my system a couple of times and Prey is still only showing only CPU information.

I'm currently using Prey 1.6.1 on my laptop (Debian Sid).

**Comment by leeyuentuen** [comment]
yes for me it is still got this problem
on ubuntu 16.04 with version 1.6.1

**Comment by javo** [comment]
Hi @leeyuentuen, @renanmarks,
I'm reviewing this problem and I could notice that sometimes in linux some information isn't specified, for virtual machines for example. However the case of @renanmarks is specially weird so i'd like to ask you both to run these commands in the terminal `dmidecode` and `ifconfig`, then post it in here. That would be really useful to help me debug this issue.

**Comment by renanmarks** [comment]
Hello @javo !
Indeed: my system is running in "bare metal", not inside a VM. I've attached the outputs you requested.
Thanks!

[dmi.txt](https://github.com/prey/prey-node-client/files/384333/dmi.txt)
[ifconfig.txt](https://github.com/prey/prey-node-client/files/384334/ifconfig.txt)

**Comment by leeyuentuen** [comment]
[ifconfig.txt](https://github.com/prey/prey-node-client/files/388395/ifconfig.txt)
[dmidecode.txt](https://github.com/prey/prey-node-client/files/388396/dmidecode.txt)

I've hide some information

@javo

**Comment by javo** [comment]
Awesome guys! Thank you!
I'm gonna be checking this now, I'm counting on having a fix for next release.
