### ISSUE TITLE
Prey v1.5.0 Mac. Unable to initialize. Service exits error code 11.

### ISSUE THREAD

**Issue by robflate** [prey/prey-node-client#180]
Noticed my Retina Macbook Pro (10.11.2) was unavailable on Prey website. Installed Prey 1.5.0 and it briefly appeared then became unavailable. Console log shows;

```
26/12/2015 00:42:04.838 com.apple.xpc.launchd[1]: (com.prey.agent[62373]) Service could not initialize: Unable to set current working directory. error = 2: No such file or directory, path = /usr/lib/prey/current: 15C50: xpcproxy + 12028 [1353][13E77DA5-3602-31BF-B074-49D4EE27E9D8]: 0x2
```

every 10 seconds then finally shows;

```
26/12/2015 00:44:23.024 com.apple.xpc.launchd[1]: (com.prey.agent[62441]) Service exited with abnormal code: 11
```

Is this a bug or something specific about my setup? Thanks.

**Comment by steakknife** [comment]
`1/16/16 12:02:06.882 AM com.apple.xpc.launchd[1]: (com.prey.agent[92]) Service exited with abnormal code: 11` here too.

**Comment by casenjo** [comment]
Got the same message, I haven't been able to get it tracking on the website.
I tried uninstalling it completely, then rebooting, and then reinstalling it but that didn't fix much. The abnormal code message is gone but on my control panel I get the message "Unable to get the devices location on time.". When I run

```
/usr/local/lib/prey/current/bin/prey --run "get location"
```
it prints out the JSON data for the location just fine though.

On a 2012 MBP with El Capitan 10.11.3.

**Comment by nachimir** [comment]
Currently getting the same log message with Prey 1.6.1 and El Capitan 10.11.5

`01/07/2016 23:04:00.247 com.apple.xpc.launchd[1]: (com.prey.agent[86]) Service exited with abnormal code: 11`

Prey can install successfully, runs, but after a reboot reinstalling Prey seems to be the only way to get it running again.
