### ISSUE TITLE
OS X El Capitan, cannot connect to Prey server after installing v1.5.0

### ISSUE THREAD

**Issue by manuelmeurer** [prey/prey-node-client#181]
I noticed my Mac said "last seen 3 months ago" in the Prey panel, and saw [this error](https://github.com/prey/prey-node-client/issues/147) in my system log, so I installed Prey 1.5.0. The installation went fine, however when the "Prey Configurator" (Python) was launched, I couldn't log in with my credentials. It would take a long time and finally a popup with only "(502)" would appear.
When I try to verify my account from the command line, the same happens:

```
/usr/local/lib/prey/current $ bin/prey config account verify --current
Error! Unable to verify keys: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```

**Comment by raliste** [comment]
Service was down for 1 hour and 47 minutes. Is back up as of this writing.

**Comment by manuelmeurer** [comment]
Thanks, Rodrigo, it works now!
Is there a status page where one could check for scheduled maintenance in such a case in the future?

**Comment by raliste** [comment]
Yes @manuelmeurer !. We recently updated our public status website and it's available at https://preyproject.statuspage.io/

**Comment by manuelmeurer** [comment]
Sweet, thanks! :+1:

**Comment by petremoroca** [comment]
Hi there, I'm having the same issue and i checked https://preyproject.statuspage.io/ page there was no incidents reported. 
Any suggestions ?
Thanks
