### ISSUE TITLE
Prey 1.5.0 stops tracking after reboot on GalliumOS

### ISSUE THREAD

**Issue by geoff-wark** [prey/prey-node-client#183]
I have been having trouble getting Prey to work on [GalliumOS](https://galliumos.org/) (based on Xubuntu 15.04) and have tried installing from multiple sources including: Apt, .deb, npm, npm pulling from this GitHub repo. . . . The furthest I get is with npm from GitHub which will work as expected after 'prey config gui'. At this point, all functionality is there and I can verify the info from Prey Panel. Upon a reboot though, my laptop's info is no longer being tracked. Running or re-running various commands tells me that the client believes itself to be setup properly.

This behavior persists until I purge and reinstall Prey (obviously not good). Any advice? Thank you!

**Comment by raliste** [comment]
Hi @geoff-wark,

Would you be able to send a copy of the **/var/log/prey.log** file?

**Comment by geoff-wark** [comment]
Well, this is peculiar. After this install, things seem to be working fine (rebooted twice to check). For completion's sake, attached is a copy of my prey.log.

[prey.log.txt](https://github.com/prey/prey-node-client/files/81471/prey.log.txt)

Sorry to bother. Thanks for the speedy reply. I think my issue may have mostly stemmed from not running 'sudo prey config hooks post_install' after the install as the output suggests (this advice got covered up by the ending output for me).

**Comment by raliste** [comment]
It's a good thing is now working for you, and you might be just right about the post_install hook.

Don't hesitate to add a new issue should you encounter any other problem. Have a great day!
