### ISSUE TITLE
Support for SteamOS

### ISSUE THREAD

**Issue by beniwtv** [prey/prey-node-client#185]
Hi,

I'd like to use prey on my expensive gaming rig :)
However, I get "Error! Invalid os:  does not exist." when configuring.

$ lsb-release -a
No LSB modules are available.
Distributor ID:	SteamOS
Description:	SteamOS 2.0
Release:	        2.0
Codename:	brewmaster

$ cat /etc/issue
SteamOS GNU/Linux 8 \n \l

Thanks!

**Comment by boris** [comment]
Hi @beniwtv,

I've just summited a pull request with the fix to this issue. Should be in production later today.

Thanks.

**Comment by boris** [comment]
@beniwtv the fix for this issue is already in production. Please check again and feel free to open an issue if you have further problems
