### ISSUE TITLE
At least one of the following is required: uuid serial_number bios_vendor

### ISSUE THREAD

**Issue by Skoddd** [prey/prey-node-client#199]
---- ACTION DETAILS ----

Action Performed:
1. Go to https://panel.preyproject.com/signup and create a new user profile;
2. Download Prey installation file v.1.5.1 for Windows 8.1
3. Run the installation file of the file v.1.5.1 ;
4. When prompted by Prey Configurator to choose between installation as New User or Existing User, check Existing User and push Next button;
5. Fill in the fields with your Prey account credentials as done in https://panel.preyproject.com/signup;
6. Observe the result

Prey Configurator

Linking device...
Error! Invalid hardware.base: At least one of the following is required: uuid serial_number bios_vendor
OK 

I have a lenovo y50

**Comment by Skoddd** [comment]
thanks for the responses guy, you've been really helpful !

**Comment by javo** [comment]
Hello @Skoddd, we're very sorry for the delay but we've been with a lot of stuff to care of. 
I'm currently reviewing this issue and I'd like to know if you still have it. If that's the case I was wondering if you could help me debug this issue running some commands in the prompt, I have an idea but I need confirmation from somebody who has it.
I hope you can be able to help me.

**Comment by jbmorris289** [comment]
I am also having this error, and I'm on Windows XP: 
![screenshot_48hf](https://cloud.githubusercontent.com/assets/22121073/18412811/e4fd3030-775d-11e6-9744-2cf7bc5c2ecc.png)
I am on version 1.6.3 with this error.

**Comment by javo** [comment]
Hey @jbmorris289,
We believe this problem occurs because there's  a problem with the system files on your pc.
Try running the command prompt, with administrator provileges, and use this command: 'sfc /scannow'. The process can take a while but should be enough to repair your system files.
Then try installing Prey again.
Let me know how it goes :)

**Comment by jbmorris289** [comment]
@Skoddd OK, I've tried sfc /scannow, and I get this:
![snip41](https://cloud.githubusercontent.com/assets/22121073/18420390/6a0f52e2-7837-11e6-8ca6-95b71505a0a7.jpg)
I don't have an XP professional CD, I have a multilingual CD from MSI with XP Home. This XP Computer is a Netbook, So I had to convert it to ISO and use ImDisk to mount it.

**Comment by javo** [comment]
I did a little research and the only thing I can suggest you for now is to get an XP Professional ISO that you can mount it using ImDisk and then try to run the command again.
I'll let you know if I can came up with another solution.

**Comment by jbmorris289** [comment]
Sorry for the late reply.
Well, I tried that, got the same message.

**Comment by santipl** [comment]
I have the same error since version 1.6.3 to 1.6.5 in Windows 10.

**prey.log:**
PREY 1.6.5 spreads its wings!
  Current time: Tue Feb 21 2017 14:23:57 GMT-0300 (Argentina Standard Time)
  Running with PID 14224 as UserName over Node.js v4.4.5 on a ia32 windows system (undefined)

     info Tue, 21 Feb 2017 17:23:57 GMT [control-panel] Gathering device data...
     info Tue, 21 Feb 2017 17:23:57 GMT [reports] Gathering specs report.
    error Tue, 21 Feb 2017 17:23:57 GMT [reports] Unable to get storage_devices_list: TODO!
    error Tue, 21 Feb 2017 17:23:57 GMT [reports] Unable to get network_interfaces_list: Unable to find wmic command in path.
     info Tue, 21 Feb 2017 17:23:57 GMT [reports] Report gathered: specs
    error Tue, 21 Feb 2017 17:24:16 GMT [control-panel] Unable to register device: Invalid hardware.base: At least one of the following is required: uuid serial_number bios_vendor
     warn Tue, 21 Feb 2017 17:24:16 GMT [control-panel] Not configured. Waiting for user input...
     info Tue, 21 Feb 2017 17:24:26 GMT [control-panel] Reloading config...
     info Tue, 21 Feb 2017 17:24:36 GMT [control-panel] Reloading config...
     info Tue, 21 Feb 2017 17:24:46 GMT [control-panel] Reloading config...
     info Tue, 21 Feb 2017 17:24:56 GMT [control-panel] Reloading config...

**Comment by javo** [comment]
Hi @santipl,
Could you run this: `wmic bios get serialnumber` in your command prompt as Administrator and type here the answer please?

**Comment by santipl** [comment]
Hi @javo, here's the answer:
'wmic' is not recognized as an internal or external command,
operable program or batch file.

**Comment by javo** [comment]
Ok, I believe there's a problem with you system files, because 'wmic' should be recognizable.
Now try running `sfc /scannnow`, that should fix the problem. When the process it's done run `taskkill /f /im node.exe` to reset the prey client and check if it's working fine.

**Comment by santipl** [comment]
I already run "sfc /scannnow" but no issue was found. I run "taskkill /f /im node.exe" wich gave me a success message. And run "prey config gui -f" but no luck.

**Comment by javo** [comment]
Hmmm.. ok... now run `where wmic`

**Comment by santipl** [comment]
> INFO: Could not find files for the given pattern(s).

**Comment by javo** [comment]
Now this.. `SET PATH=C:\Windows\System32\wbem\;%PATH%;`, then `where mic` again

**Comment by santipl** [comment]
After setting that path and run `where wmic` I got:

> C:\Windows\System32\wbem\WMIC.exe

**Comment by santipl** [comment]
And now running 'wmic bios get serialnumber' gives me a serial number..

**Comment by javo** [comment]
Ok great! Now try again with `wmic bios get serialnumber`. If you get your serial number, then the command is fixed and Prey should be working. Let me know :)

**Comment by javo** [comment]
Awesome! Check with Prey now :)

**Comment by santipl** [comment]
![preysuccess](https://cloud.githubusercontent.com/assets/14061654/23179478/cd51a5a4-f84c-11e6-9b0d-4ccbe23008d4.PNG)

**Comment by javo** [comment]
Great! Glad I could help ^^

**Comment by santipl** [comment]
Thanks!!!!!!!!!!!!!! =)
