### ISSUE TITLE
Lock screen can be remove even without a password on windows

### ISSUE THREAD

**Issue by zer09** [prey/prey-node-client#202]
Step to replicate:

- Active "Lock device".
- Now the device is locked.
- Reboot the machine after log-on the you can still access the desktop for a few seconds, then it will lock-up.
- Hit CTRL+Del then you are in the log-screen, press "Log off", then the user will log off.
- Now log-in with the same account, the prey-lock screen is unlocked.

Versions:
Windows 7 x64.
Prey 1.5.1

**Comment by cyaconi** [comment]
Hi @zer09 

Thanks for your feedback. We were able to reproduce it, and it's currently being solved.

We expect to release the fix with version 1.5.3.

Best,
