### ISSUE TITLE
enough already

### ISSUE THREAD

**Issue by bhovell2** [prey/prey-node-client#204]
Hi, Tomas ...

You will recall I forwarded corrections (authored by others) for the post-install script which did fix the persistent package install failures for prey on version 15.x Ubuntu.

However, I've just installed the new Ubuntu 16.04 version and the same behavior is back again, even when the fixed script replaces the stock one. This is once again what happens every time I run apt-get as the root user:

[....mumble, mumble...]
Running post_activate hooks...
Voila! All good.
--
Installing init scripts.
Sweet! Please run `prey config gui` to finish installation.
Voila! All good.
sudo: prey: command not found
dpkg: error processing package prey (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 prey

My new solution to this problem, therefore, is to simply remove prey from my laptop and call it good. The absolutely certain waste of my time (once again) chasing phantoms on Google far exceeds the marginal risk of theft of the laptop. My geek streak simply doesn't run deep enough to justify the repeated time lost.

My suggestion is to provide another way to successfully install prey on Ubuntu across different versions and different platforms, as package install methods plainly do not. Tarball/config/make, perhaps?

**Comment by raliste** [comment]
I would do the same, but please don't lose hope on us. The team changed
recently and we are already working on updating our distribution infra so
that we can fix this and streamline the release process.

In the mean time, have you tried installing prey via npm?

**Comment by bhovell2** [comment]
I don't see that as a selection choice on the prey menu.
