### ISSUE TITLE
Linux prey-agent service inconsistent

### ISSUE THREAD

**Issue by andyrichardson** [prey/prey-node-client#206]
The prey-agent service that runs on startup fails to return a location and presenting messages from the control pannel doesn't always happen. On the contrary, when running prey inside the terminal as a process, all these issues are no longer existent.

Version: 1.5.1
OS: Fedora 23

**Comment by raliste** [comment]
Thank you for reporting @andyrichardson.

I'll update this issue as soon as we get more information from testing.
