### ISSUE TITLE
Partial screenshots when text size is increased on Windows

### ISSUE THREAD

**Issue by ghost** [prey/prey-node-client#209]
# Problem

Prey can't grab full screenshots if you change the text size settings on Windows 10. You can find such setting under `System Configuration > Screen > Change the size of text, apps, and other items`.

This is supposed to be a 1980x1080 screenshot.

![screenshot original](https://cloud.githubusercontent.com/assets/401279/15750845/502a035e-28be-11e6-9afb-a2b557c1953e.jpg)

Ref: https://secure.helpscout.net/conversation/209925169/38847/

**Comment by camilaburgos** [comment]
New case: https://secure.helpscout.net/conversation/227035406/39952/?folderId=645877

![image001](https://cloud.githubusercontent.com/assets/10212992/17148286/841b088e-5334-11e6-92ed-13ebd19d4bcf.png)
