### ISSUE TITLE
Prey doesn't work on macOS 10.12 Sierra

### ISSUE THREAD

**Issue by yashendra2797** [prey/prey-node-client#214]
My device hasn't been connected to Prey's servers since yesterday, when I installed the Developer Beta.

I'm running Mac OS Sierra v10.12 Beta (16A201w) on my MacBook Air (13-inch, Mid 2013)

Let me know if you need some logs or need me test something out.

**Comment by raliste** [comment]
Hi @yashendra2797, could you attach the /var/log/prey.log if any?

**Comment by yashendra2797** [comment]
Hmmm. There doesn't seem to be any. 

![Screenshot of /~/Private/var/log/ folder](https://cloud.githubusercontent.com/assets/8304724/16173419/d5679eac-35be-11e6-822b-22716a27a0dc.png)

**Comment by raliste** [comment]
It probably didn't install in spite of the installer claiming it did. We are actually reviewing this issue and we should hopefully have an update by next week.

**Comment by stakano2** [comment]
I have the same issue...  My MacBook was stolen yesterday and now it can't be located because Sierra was installed...  Not a happy camper! Says that it last saw it 20 days ago which is around the time it was installed....

**Comment by corporate-gadfly** [comment]
Any progress on this? macOS Sierra is now GM candidate.

I'm running macOS 10.12 (16A320) on a MacBookPro11,3.

Here's a pastebin of a command that I ran. I exited after a few minutes as it wasn't going anywhere.
http://pastebin.com/jf4DsntH

What can we do to help further?

**Comment by fradamek** [comment]
Any updates on this? Is there any version of Prey that may work for macOS Sierra? How long before there is a solution?

**Comment by javo** [comment]
I'm currently reviewing the issue, yesterday I install Prey on MacOS 10.12 Sierra and it worked fine.
@fradamek could you paste your prey.log file? Maybe there's some clue to solve this.
I'll let you guys know if get something.

**Comment by corporate-gadfly** [comment]
@javo what about the pastebin from this comment https://github.com/prey/prey-node-client/issues/214#issuecomment-246111565?

**Comment by javo** [comment]
@corporate-gadfly since saturday we're been having some connection issues. Everything is running normal now after some system changes. Could you try running the prey client again and tell me if it's working for you?

**Comment by corporate-gadfly** [comment]
Thx for replying.

After uninstalling by following
```
sudo /usr/local/lib/prey/current/bin/prey config hooks pre_uninstall && sudo rm -rf /usr/local/lib/prey /var/log/prey.log /etc/prey
```
and reinstalling 1.6.3, I can report that the device is being seen successfully by prey. It's possible that removing `/etc/prey` helped.

**Comment by javo** [comment]
Great! Thank you for let us know :) It's probably because we got a service down, now everything should be working fine.

**Comment by corporate-gadfly** [comment]
There's something about the macOS Sierra upgrade process which breaks prey. Today, I upgraded 3 machines from 10.12 16A320 to 10.12 16A323 and on all three machines, I had to uninstall and install before prey worked.

HTH.

**Comment by fradamek** [comment]
Prey is back up and running for me after the Info from Corporte.

**Comment by wachunei** [comment]
I updated to the final release of Sierra from the macOS App Store and prey is completely gone from my machine, found out because of a mail I got saying my mac has been gone.

**Comment by corporate-gadfly** [comment]
@wachunei : From what I can tell, Prey is still there after the Sierra upgrade, but is not able to connect any more. Following instructions from https://github.com/prey/prey-node-client/issues/214#issuecomment-247015644, you should be able to get it back.

Still waiting to hear something official from the prey developers.

**Comment by wachunei** [comment]
@corporate-gadfly: I did use the installer again and it went back online. This is like the most user-friendly solution to common non-geek users so far.

**Comment by javo** [comment]
Hey everyone,
We just confirmed that upgrading to MacOS Sierra from a previous version causes Prey to stop working.
Now, the problem is that the OS upgrade deletes de prey user in charge of allowing the software to run.

In the meantime there's 2 options to fix this:
- One is just reinstalling Prey and it's gonna work fine.
- The other one is to create the prey user following the next commands, and then reboot,
```
dscl MAX_ID=$(dscl . -list /Users UniqueID | awk '{print $2}' | sort -ug | tail -1)
USER_ID=$((MAX_ID+1))

sudo dscl . -create /Users/prey
sudo dscl . -create /Users/prey UserShell /sbin/nologin
sudo dscl . -create /Users/prey RealName "Prey Anti-Theft"
sudo dscl . -create /Users/prey UniqueID "$USER_ID"
sudo dscl . -create /Users/prey PrimaryGroupID 80
sudo dscl . -delete /Users/prey AuthenticationAuthority
sudo dscl . -create /Users/prey Password "*"
```

I hope this can be helpful for now. We're working to find a solid solution to this issue.
Sorry for the inconveniences.

**Comment by danlevity** [comment]
javo, the solutions in the previous post do not work with the released Sierra 10.2.  I can create the user prey using the shell scripts, and reinstal prey on my mac, but it is not detected by Prey.  I have replicated this on four computers running Sierra.

**Comment by javo** [comment]
Hi @danlevity,
I have a question.. did you have installed prey before the upgrade to Sierra? 
It should be enough only to run the script or reinstall prey, but no both.
Could you run `sudo /usr/local/lib/prey/current/bin/prey config hooks pre_uninstall && sudo rm -rf /usr/local/lib/prey /var/log/prey.log /etc/prey`, then install prey again?. If it's still not working run this command `id -g prey` and let me know the response.
I hope that helps

**Comment by TCattd** [comment]
Reinstalled Prey (1.6.3) on top of the current installation (from before Sierra upgrade) didn't do it for me. Prey still couldn't reach my device.

Uninstalling it using @javo's instructions ( https://github.com/prey/prey-node-client/issues/214#issuecomment-254198054 ), restarting (just in case) and then reinstalling Prey did the trick for me.

**Comment by marc24** [comment]
Hi @javo,
Do you plan to push an automatic update soon ? 
Some of my computers are abroad and i can't reinstall prey or create the prey user by myself...
Thanks for your answer

**Comment by jorgearq00** [comment]
Gracias Javo, tu patch funcionó bien!

**Comment by corporate-gadfly** [comment]
Hi Prey team,

Good work by being proactive and sending out an email to possibly affected prey clients. I'm referring to the email titled "macOS Sierra update broke Prey… but you can easily fix it!" that I received today.

👍

**Comment by dlindelof** [comment]
I installed Prey today on my MacBook Air, and Prey reports it is unable to find the device. I have tried to run the patch but it reported it did not find the Sierra bug:

![image](https://cloud.githubusercontent.com/assets/245328/22651608/f258d4aa-ec83-11e6-8b7d-48b314c35801.png)

**Comment by javo** [comment]
Hi @dlindelof, could you attach your prey.log file here? The file is in the `/var/log` directory

**Comment by dlindelof** [comment]
Here you are:

```

  ████████████████ ████████████████ ████████████████ ██            ██
  ██            ██ ██               ██            ██ ██            ██
  ██            ██ ██               ████████████████ ██            ██
  ██            ██ ██               ██               ██            ██
  ████████████████ ██               ████████████████ ████████████████
  ██                                                               ██
  ██                                                 ████████████████

  PREY 1.6.5 spreads its wings!
  Current time: Mon Feb 06 2017 15:43:27 GMT+0100 (CET)
  Running with PID 52340 as prey over Node.js v4.4.5 on a x64 mac system (undefined)

     info Mon, 06 Feb 2017 14:43:30 GMT [actions] Starting action: geofencing
     info Mon, 06 Feb 2017 14:43:30 GMT [actions] Running: geofencing
     info Mon, 06 Feb 2017 14:43:30 GMT Plugin loaded: control-panel
     info Mon, 06 Feb 2017 14:43:30 GMT 1 plugins loaded with 0 errors.
     info Mon, 06 Feb 2017 14:43:30 GMT Initialized.
     info Mon, 06 Feb 2017 14:43:30 GMT [triggers] Watching: connection, network, power
     info Mon, 06 Feb 2017 14:43:30 GMT [actions] Starting trigger: connection
     info Mon, 06 Feb 2017 14:43:31 GMT [actions] Running: connection
     info Mon, 06 Feb 2017 14:43:31 GMT [actions] Starting trigger: network
     info Mon, 06 Feb 2017 14:43:31 GMT [actions] Starting trigger: power
     info Mon, 06 Feb 2017 14:43:31 GMT [actions] Running: network
     info Mon, 06 Feb 2017 14:43:31 GMT [actions] Running: power
    error Mon, 06 Feb 2017 14:43:35 GMT Error: Geofences list is not an array
     info Mon, 06 Feb 2017 14:43:35 GMT [actions] Stopped: geofencing
     warn Mon, 06 Feb 2017 14:43:35 GMT [control-panel] Unable to sync settings.
     info Mon, 06 Feb 2017 14:43:35 GMT [actions] Starting action: geofencing
     info Mon, 06 Feb 2017 14:43:36 GMT [actions] Running: geofencing
    error Mon, 06 Feb 2017 14:43:38 GMT Error: Geofences list is not an array
     info Mon, 06 Feb 2017 14:43:38 GMT [actions] Stopped: geofencing
```

**Comment by javo** [comment]
I believe there's an issue with your connection, it's there a way you can try connecting using another wifi network and check if the device it's available in the prey panel?

**Comment by dlindelof** [comment]
Not immediately, no. But I'll try again tonight from home.

**Comment by javo** [comment]
ok @dlindelof, let me know how it goes :)

**Comment by dlindelof** [comment]
Here is what I see in the logfile on the wifi at home:

```
    error Mon, 06 Feb 2017 19:36:51 GMT [network] Connection error: Error: socket hang up
    error Mon, 06 Feb 2017 19:36:56 GMT [network] Connection error: Error: getaddrinfo ENOTFOUND solid.preyproject.com solid.preyproject.com:443
    error Mon, 06 Feb 2017 19:36:56 GMT [network] Connection error: Error: getaddrinfo ENOTFOUND solid.preyproject.com solid.preyproject.com:443
     info Mon, 06 Feb 2017 19:37:08 GMT [actions] Starting action: geofencing
     info Mon, 06 Feb 2017 19:37:08 GMT [actions] Running: geofencing
    error Mon, 06 Feb 2017 19:37:08 GMT Error: Geofences list is not an array
     info Mon, 06 Feb 2017 19:37:08 GMT [actions] Stopped: geofencing
```

In fact I don't see any of my devices. When I select one of them, say the iPhone, I get a notification on my iPhone from Prey (the camouflaged one), and only if I open Prey on the iPhone will its location be updated.

![image](https://cloud.githubusercontent.com/assets/245328/22663489/0e670dc8-ecad-11e6-85a2-7759bbf3bdeb.png)

**Comment by javo** [comment]
Please try accessing https://solid.preyproject.com/test from your pc and your iPhone and attach a screenshot here for both cases, so we can discard some connection problems.

**Comment by dlindelof** [comment]
From the Mac:

![image](https://cloud.githubusercontent.com/assets/245328/22665626/b6f5e9c0-ecb5-11e6-8711-eac25e139a17.png)

From the iPhone:

![img_9753 2](https://cloud.githubusercontent.com/assets/245328/22665692/f4fcb8ac-ecb5-11e6-8c8f-b7771f8cf90e.PNG)

**Comment by javo** [comment]
Try restarting your mac, then run this command `sudo pkill -f prx` in your terminal.

**Comment by dlindelof** [comment]
It seems to work now; the MacBook is now seen in the dashboard and I can send a message to it. I can also see my iPad. But my iPhone remains unreachable. Should I open a separate issue about that?

**Comment by javo** [comment]
I'm glad that is working now on your Macbook :) Sadly i can't help you with your iPhone because Prey runs on it using a different client. If you have a Pro account you can use the support service through the Help button in your account, otherwise you can use Twitter or Facebook to ask for it.

**Comment by dlindelof** [comment]
Ok thanks :-)

**Comment by cosmetik** [comment]
Hi there!, Upgrading to sierra 10.12.5 now makes prey unavailable in mbp. 
Steps done:
- Reinstall prey in mbp
- restart and run "sudo pkill -f prx" 
- run the patch. it reads that didnt found any bug
- check out the connectivity test
- Delete the device in the panel
- Reinstall again prey and when im trying to put the device in the panel im not able to link the computer

any directions would be appreciated. 
Thanks!

Here are the connectivity tests suggested by javo:
    IP Trace: 107.178.244.155
    Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0
    profile.json completed with trace preyfrontend, @all_to_bullet (66 ms)
    signup.json completed with trace preyfrontend, @all_to_bullet (94 ms)
    Latency Test: 86 ms (1.62, 1.12)

**Comment by wachunei** [comment]
I'm having the same issue now with High Sierra update. Is @javo patch okay to use again?

**Comment by shenanigans12** [comment]
I successfully used these instructions to solve the issue with the High Sierra update. But @javo , you guys should really push out a fix via an update, your average end user is not going to know that there is a problem, let alone how to find these instructions and use the command line.

**Comment by mikchar** [comment]
Prey stopped working on my mac about 30 days ago.
I have not made any major change or update last month.
could it be when prey got upgraded to 1.8.2?
I try what is being suggested on this page but still not working.
The test result is:

    IP Trace: 209.58.133.168, 107.178.244.155
    Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:63.0) Gecko/20100101 Firefox/63.0
    profile.json error
    Signup: pending
    Latency Test: 386 ms (0.45, 0.33)

any suggestion of what else I could try?

**Comment by javo** [comment]
Hi @mikchar, can I check your /var/log/prey.log file?

**Comment by mikchar** [comment]
Here is the file
[prey.log](https://github.com/prey/prey-node-client/files/2773238/prey.log)

**Comment by mikchar** [comment]
Yes, it works now.
For some reasons, it didn't work in Firefox, I had to do it inside Safari.
Thanks for your help !
