### ISSUE TITLE
Can't install prey on osx el capitan 10.11.4

### ISSUE THREAD

**Issue by redandgold45** [prey/prey-node-client#218]
I've tried to install prey at least a dozen times, but every time I go to check the device dashboard on the website, it says the device is unavailable.

**Comment by raliste** [comment]
Hi @redandgold45,

Was your problem recent, say, today? We had a slight server outage a couple of hours ago that didn't allow dashboard-device communication.

**Comment by javo** [comment]
Hello @redandgold45, were you able to contact with your device?. Please let us know if you still are having troubles.
