### ISSUE TITLE
"Error! Unable to verify keys" and other oddities (v 1.6.1 on OSX 11.11.5

### ISSUE THREAD

**Issue by paxperscientiam** [prey/prey-node-client#219]
Hello all,

I'm currently running into issues with v. 1.6.1. The Control panel simply cannot reach my device -- except when I run "prey config gui" and go through the process. After which, the Control panel does connect with my device; however, further attempts to send commands to my device or locate my device fail.

When I run the command "prey config check", prey outputs "Checking installation. Error! Unable to verify keys." This is odd for two reasons: 1) presumably, if the GUI version of config can verify keys, why can't the command line version? 2) the API and device keys are as they always were.

I thought, perhaps, this was a permissions related issue, but prey owns both both the "/etc/prey" and "/etc/prey/prey.conf".

Any suggestions on how to fix this? It's disconcerting to discover that prey had not been protecting my computer for a while.

**Comment by karlicoss** [comment]
Same with 1.6.1 and ubuntu 16.04, can't verify the keys, control panel won't connect.

Also, there is some something like that: "GMT Error: Unknown command: undefined" in logs..

**Comment by karlicoss** [comment]
Quick inspection of the `resp` variable in `verify_keys` function shows that server responds with statusCode: 500, statusMessage: 'Internal Server Error'.

**Comment by javo** [comment]
Hey guys, this issue is now fixed for the last node client version 1.6.4
