### ISSUE TITLE
Prey on SailfishOS 2.0.2.48 armv7l / i486

### ISSUE THREAD

**Issue by explit7** [prey/prey-node-client#224]
Hello guys. we have a big trouble to install prey on Sailfish OS Version 2.0.2.48 (i486 / armv7l)

Early versions of Sailfish OS were supported on the Jolla phone.
No we get the same

Error! Invalid os: does not exist.

Which information do you need to support the newer versions of sailfish OS?

Here what the lsb-release -a gives out on a 
## Jolla Phone JP-1501 / Fairphone2 with Sailfish 2.0.2.48 armv7l

```
Do you already have a Prey account?
yes/no: [yes] 
Well hello old friend! Please type your account's email address.
email: ex****@.*** 
Well played. Now enter your password.
pass: *********** 
Credentials verified. 
Linking device...
Error! Invalid os: does not exist.
```

---

Jolla Phone JP-1301 / Fairphone 2 SailfishOS 2.0.2.48 armv7l

```
[root@localhost nemo]# lsb_release -a
LSB Version: :core-3.1-arm:core-3.1-noarch:core-3.2-arm:core-3.2-noarch:core-4.0-arm:core-4.0-noarch:desktop-3.1-arm:desktop
-3.1-noarch:desktop-3.2-arm:desktop-3.2-noarch:desktop-4.0-arm:desktop-4.0-noarch
Distributor ID: #Thisfileiscopiedashw-release(analogoustoos-release)
Description: # This file is copied as hw-release (analogous to os-release)
Release: n/a
Codename: analogoustoos-release
```

Jolla Tablet JT-1501 SailfishOS 2.0.2.48 i486

```
[root@Sailfish nemo]# lsb_release -a
LSB Version: :core-3.1-ia32:core-3.1-noarch:core-3.2-ia32:core-3.2-noarch:core-4.0-ia32:core-4.0-noarch:desktop-3.1-ia32:des
ktop-3.1-noarch:desktop-3.2-ia32:desktop-3.2-noarch:desktop-4.0-ia32:desktop-4.0-noarch
Distributor ID: #Thisfileiscopiedashw-release(analogoustoos-release)
Description: # This file is copied as hw-release (analogous to os-release)
Release: n/a
Codename: analogoustoos-release
```

Please add this Sailfish Version to the list of recognised OSes.

Thanks

**Comment by explitit** [comment]
Please add Sailfish 2.0.2.48 to the know OS


lsb_release -ri :

Distributor ID: #Thisfileiscopiedashw-release(analogoustoos-release)
Release: n/a
[root@Sailfish nemo]#
@explitit
explitit commented 2 days ago

lsb_release

LSB Version: :core-3.1-arm:core-3.1-noarch:core-3.2-arm:core-3.2-noarch:core-4.0-arm:core-4.0-noarch:desktop-3.1-arm:desktop-3.1-noar
ch:desktop-3.2-arm:desktop-3.2-noarch:desktop-4.0-arm:desktop-4.0-noarch
[root@Sailfish nemo]#

**Comment by nieldk** [comment]
I figured a workaround out. The issue is really not with Prey, but with Jolla  lsb_release files are not correct

specifically, we need to change the file

**/etc/hw-release**

by adding this line to the top of the file

**Mer release 02011 Jolla**

This will allow to setup the account and activate it on Prey servers
