### ISSUE TITLE
Prey 1.6.1 in Ubuntu 14.04 unable to reach device

### ISSUE THREAD

**Issue by victortxa** [prey/prey-node-client#225]
After installing prey 1.6.1 via `sudo dpkg -i prey_1.6.1_amd64.deb`, then:

>  Running
> ##  "config activate" as prey
> 
> Ensuring presence of config dir: /etc/prey
> Syncing /etc/prey/prey.conf with /usr/lib/prey/versions/1.6.1/prey.conf.default
> Setting up this as current...
> No version is set as current.
> Setting permissions on /usr/lib/prey/current
> Running post_activate hooks...
> ## Voila! All good.
> 
> Installing init scripts.
> Sweet! Please run `prey config gui` to finish installation.
> Voila! All good.
> localuser:prey being added to access control list
> Firing up config GUI! 

I entered my account info in the GUI and the laptop is added in my Prey account. However, Prey is not able to get the location of it.

**Comment by johnkrovitch** [comment]
same issue here on KDE Neon (ubuntu 16.04). I have Prey installed and configured, I see the device in th Prey website, but location and actions to this device are not working : "Unable to reach device"

Any idea ? Thanks

**Comment by javo** [comment]
Hi @johnkrovitch can I see your /var/log/prey.log file?

**Comment by johnkrovitch** [comment]
warn Thu, 23 Mar 2017 09:27:34 GMT Got QUIT signal.
     info Thu, 23 Mar 2017 09:27:34 GMT Gracefully shutting down. Will self-destruct in 10 secs.
     info Thu, 23 Mar 2017 09:27:34 GMT [hooks] Unregistering hooks.
     info Thu, 23 Mar 2017 09:27:40 GMT [control-panel] Reloading config...
     info Thu, 23 Mar 2017 09:27:44 GMT Time's up, shutdown forced. Have a jolly good day sir.
 and nothing since this date.

**Comment by johnkrovitch** [comment]
I have some custom rules in my /etc/hosts for web development purpose. Maybe is it related ?

**Comment by sergiobenrocha2** [comment]
Same issue here

**Comment by sergiobenrocha2** [comment]
Had to downgrade to 1.4.2, seems it's working, it can reach my laptop, but I can't send messages
