### ISSUE TITLE
Location is being obtained by Geoip instead of Wi-Fi possition system on Windows

### ISSUE THREAD

**Issue by camilaburgos** [prey/prey-node-client#227]
The problem happened to one customer running Windows 10. 

After running **netsh wlan show all**, several Wi-Fi networks showed up. She's also not connected via Ethernet, but Wi-Fi.

She also tried disabling the native **Location Services** from Windows. Nothing happened. 

References: 
- https://secure.helpscout.net/conversation/241055765/40972/?folderId=131892

**Comment by egaille** [comment]
Hi, 
I have the same problem on a Macbook 12" (2015) under windows 10. 

I have a dual-boot with : 
- OSX 10.12.4
- Windows 10 x64 1607 freshly updated to 1709 (Fall creator's update (october 2017)

1) under OSX, everything works fine : Both Google-Maps and Prey are locating my macbook correctly and precisely. 
2) under Windows 10 (both 1607 and 1709 versions), google-maps is locating correctly, **but Prey is showing a location 200 miles away from my actual location !**

I have tried enabling and disabling windows location feature, deactivating the firewall, uninstalling and re-installing Prey 1.7.0 and 1.7.1 (no success with both versions).

Indeed when i do a **netsh wlan show all**, several Wi-Fi networks showed up.

Here is the Prey log file : 
`PREY 1.7.1 spreads its wings!
  Current time: Wed Nov 01 2017 23:57:11 GMT+0100 (Paris, Madrid)
  Running with PID 7676 as MACBOOK_MANU_ over Node.js v4.4.5 on a x64 windows system (undefined)

     warn Wed, 01 Nov 2017 22:57:12 GMT [control-panel] Not configured. Waiting for user input...
     info Wed, 01 Nov 2017 22:57:22 GMT [control-panel] Reloading config...
     info Wed, 01 Nov 2017 22:57:32 GMT [control-panel] Reloading config...
     info Wed, 01 Nov 2017 22:57:42 GMT [control-panel] Reloading config...
     info Wed, 01 Nov 2017 22:57:52 GMT [control-panel] Reloading config...
     info Wed, 01 Nov 2017 22:57:52 GMT Plugin loaded: control-panel
     info Wed, 01 Nov 2017 22:57:52 GMT 1 plugins loaded with 0 errors.
     info Wed, 01 Nov 2017 22:57:52 GMT Initialized.
     info Wed, 01 Nov 2017 22:57:52 GMT [triggers] Watching: connection, control-zones, location, network, power
     info Wed, 01 Nov 2017 22:57:52 GMT [actions] Starting trigger: connection
     info Wed, 01 Nov 2017 22:57:52 GMT [actions] Running: connection
     info Wed, 01 Nov 2017 22:57:52 GMT [actions] Starting trigger: control-zones
     info Wed, 01 Nov 2017 22:57:52 GMT [actions] Running: control-zones
     info Wed, 01 Nov 2017 22:57:52 GMT [actions] Starting trigger: location
     info Wed, 01 Nov 2017 22:57:52 GMT [actions] Running: location
     info Wed, 01 Nov 2017 22:57:52 GMT [actions] Starting trigger: network
     info Wed, 01 Nov 2017 22:57:52 GMT [actions] Starting trigger: power
     info Wed, 01 Nov 2017 22:57:53 GMT [actions] Running: network
     info Wed, 01 Nov 2017 22:57:53 GMT [actions] Running: power
     notice Wed, 01 Nov 2017 22:57:53 GMT [control-panel] Updating value of auto_connect to true
     info Wed, 01 Nov 2017 22:57:57 GMT [reports] Gathering status report.
    error Wed, 01 Nov 2017 22:57:57 GMT [reports] Unable to get active_access_point: No access points found.
     info Wed, 01 Nov 2017 22:57:57 GMT [reports] Report gathered: status
     info Wed, 01 Nov 2017 22:57:57 GMT [control-panel] Posting event
     info Wed, 01 Nov 2017 22:57:58 GMT [control-panel] Got 200 response: Ok mate.
     info Wed, 01 Nov 2017 22:59:03 GMT [long-polling] Got 1 commands.
     info Wed, 01 Nov 2017 22:59:06 GMT [reports] Gathering status report.
    error Wed, 01 Nov 2017 22:59:07 GMT [reports] Unable to get active_access_point: No access points found.
     info Wed, 01 Nov 2017 22:59:07 GMT [reports] Report gathered: status
     info Wed, 01 Nov 2017 22:59:07 GMT [control-panel] Posting data
     info Wed, 01 Nov 2017 22:59:07 GMT [control-panel] Got 200 response: OK
     info Wed, 01 Nov 2017 22:59:32 GMT [long-polling] Got 1 commands.
     info Wed, 01 Nov 2017 22:59:35 GMT [reports] Gathering status report.
    error Wed, 01 Nov 2017 22:59:36 GMT [reports] Unable to get active_access_point: No access points found.
     info Wed, 01 Nov 2017 22:59:36 GMT [reports] Report gathered: status
     info Wed, 01 Nov 2017 22:59:36 GMT [control-panel] Posting data
     info Wed, 01 Nov 2017 22:59:36 GMT [control-panel] Got 200 response: OK
`
It clearly shows an error : **"Unable to get active_access_point: No access points found."**, but i couldn't find any information on the internet, except this bug-report thread. And i don't know where to look for. 
My laptop is always connected with the internal wifi adapter (no Ethernet adapter on the machine).

Please please help.
