### ISSUE TITLE
Unable to install. Prey 1.6.2. Windows 8.1 x64

### ISSUE THREAD

**Issue by xpoft** [prey/prey-node-client#234]
`
=== Logging started: 01.09.2016  23:41:52 ===
Action start 23:41:52: INSTALL.
Action start 23:41:52: FindRelatedProducts.
Action ended 23:41:52: FindRelatedProducts. Return value 1.
Action start 23:41:52: SetSetApiKeyWithoutValidation.
Action ended 23:41:52: SetSetApiKeyWithoutValidation. Return value 1.
Action start 23:41:52: SetValidateAndSetApiKey.
Action ended 23:41:52: SetValidateAndSetApiKey. Return value 1.
Action start 23:41:52: AppSearch.
Action ended 23:41:52: AppSearch. Return value 1.
Action start 23:41:52: SetCommandConfigHooksPostInstall.
Action ended 23:41:52: SetCommandConfigHooksPostInstall. Return value 1.
Action start 23:41:52: ValidateProductID.
Action ended 23:41:52: ValidateProductID. Return value 1.
Action start 23:41:52: CostInitialize.
Action ended 23:41:52: CostInitialize. Return value 1.
Action start 23:41:52: FileCost.
Action ended 23:41:52: FileCost. Return value 1.
Action start 23:41:52: CostFinalize.
Action ended 23:41:52: CostFinalize. Return value 1.
Action start 23:41:52: InstallValidate.
Action ended 23:41:52: InstallValidate. Return value 1.
Action start 23:41:52: RemoveExistingProducts.
Action ended 23:41:52: RemoveExistingProducts. Return value 1.
Action start 23:41:52: SetPostInstallRollback.
Action ended 23:41:52: SetPostInstallRollback. Return value 1.
Action start 23:41:52: SetValidateAndSetApiKeyRollback.
Action ended 23:41:52: SetValidateAndSetApiKeyRollback. Return value 1.
Action start 23:41:52: InstallInitialize.
Action ended 23:41:52: InstallInitialize. Return value 1.
Action start 23:41:52: ProcessComponents.
Action ended 23:41:53: ProcessComponents. Return value 1.
Action start 23:41:53: UnpublishFeatures.
Action ended 23:41:53: UnpublishFeatures. Return value 1.
Action start 23:41:53: RemoveRegistryValues.
Action ended 23:41:53: RemoveRegistryValues. Return value 1.
Action start 23:41:53: RemoveFiles.
Action ended 23:41:53: RemoveFiles. Return value 0.
Action start 23:41:53: InstallFiles.
Action ended 23:41:54: InstallFiles. Return value 1.
Action start 23:41:54: WriteRegistryValues.
Action ended 23:41:54: WriteRegistryValues. Return value 1.
Action start 23:41:54: RegisterUser.
Action ended 23:41:54: RegisterUser. Return value 1.
Action start 23:41:54: RegisterProduct.
Action ended 23:41:54: RegisterProduct. Return value 1.
Action start 23:41:54: PublishFeatures.
Action ended 23:41:54: PublishFeatures. Return value 1.
Action start 23:41:54: PublishProduct.
Action ended 23:41:54: PublishProduct. Return value 1.
Action start 23:41:54: CommandConfigHooksPostInstall.
Action ended 23:41:54: CommandConfigHooksPostInstall. Return value 1.
Action start 23:41:54: PostInstallRollback.
Action ended 23:41:54: PostInstallRollback. Return value 1.
Action start 23:41:54: ValidateAndSetApiKeyRollback.
Action ended 23:41:54: ValidateAndSetApiKeyRollback. Return value 1.
Action start 23:41:54: InstallFinalize.
CAQuietExec:  Ensuring presence of config dir: C:\WINDOWS\Prey
CAQuietExec:  Syncing C:\WINDOWS\Prey\prey.conf with C:\Windows\Prey\versions\1.6.2\prey.conf.default
CAQuietExec:  Setting up this as current...
CAQuietExec:  No version is set as current.
CAQuietExec:  Setting permissions on C:\Windows\Prey\current
CAQuietExec:  Running post_activate hooks...
CAQuietExec:  Removing firewall rule for C:\Windows\Prey\versions\1.6.2\bin\node.exe
CAQuietExec:  Adding firewall rule for C:\Windows\Prey\versions\1.6.2\bin\node.exe
CAQuietExec:  Installing init scripts.
CAQuietExec:  Error! Command failed: C:\WINDOWS\system32\cmd.exe /s /c "sc create CronService binPath= "C:\Windows\Prey\wpxsvc.exe" start= auto error= normal DisplayName= "Cron Service""
CAQuietExec:  Error 0x80070001: Command line returned an error.
CAQuietExec:  Error 0x80070001: CAQuietExec Failed
CustomAction CommandConfigHooksPostInstall returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 23:42:05: InstallFinalize. Return value 3.
Action ended 23:42:14: INSTALL. Return value 3.
MSI (s) (F0:7C) [23:42:14:871]: Product: Prey Anti-Theft -- Installation failed.

MSI (s) (F0:7C) [23:42:14:871]: Установщик Windows выполнил установку продукта. Продукт: Prey Anti-Theft. Версия: 1.6.2. Язык: 1033. Изготовитель: Prey, Inc.. Установка завершена с состоянием: 1603.

=== Logging stopped: 01.09.2016  23:42:14 ===
`

**Comment by javo** [comment]
Hey @xpoft, thank you for let us know.
We've had this issue for a while now and for this version i manage to solved one kind of it's behavior (the one I could reproduce). Comparing both of the logs I can tell that the issue is almost the same. I'm gonna check it again and I'll let you know as soon I have a solution.
Sorry for the inconvenience.

**Comment by benad** [comment]
Looks like you only packaged Mac binaries of sqlite3 in your Windows packaging: https://gist.github.com/benad/ab0f7d9512cf544c78b5a5e5f1746c9f . This makes the silent updater run in an endless loop of attempting to launch the "prey" process through node, consuming all the CPU on every Windows machine.

```
C:\Users\benad>C:\Windows\Prey\current\bin\prey console
module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\Windows\Prey\versions\1.6.2\node_modules\sqlite3\lib\binding\node-v46-win32-ia32\node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Windows\Prey\versions\1.6.2\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

I downloaded prey-linux-1.6.2-x86.zip, and in it I found the following:

```
$ tree prey-1.6.2/node_modules/sqlite3/lib/
prey-1.6.2/node_modules/sqlite3/lib/
├── binding
│   └── node-v46-darwin-x64
│       └── node_sqlite3.node
├── index.js
├── sqlite3.js
└── trace.js

2 directories, 4 files
```

**Comment by javo** [comment]
Hi @benad, your Windows machine is x64 or x86?

**Comment by benad** [comment]
Windows 10 x64

**Comment by javo** [comment]
So, did you download the prey client 1.6.2 for x64?

**Comment by benad** [comment]
It self-updated from 1.6.1 to 1.6.2, and the service kept in a loop of crashing and attempting to restart the node process. The log file remained empty.

**Comment by javo** [comment]
Could you please uninstall prey from your machine and download the x64 version from https://github.com/prey/prey-node-client/releases and re-install it?
Let me know how it goes please.
I also notice that i had a mistake uploading the zip linux packages, i'm gonna solve that right now.

**Comment by benad** [comment]
The x64 version installed without problem. It should be noted that your web site only offered the 32 bit version http://preyproject.com/download , so my machine was already running 1.6.1 in 32 bit without problem and started crashing continuously after the selfupdate.

**Comment by javo** [comment]
Yes, I'm gonna fix that.
Thanks for your help @benad
