### ISSUE TITLE
Device missing - macos sierra

### ISSUE THREAD

**Issue by HerbSomersal** [prey/prey-node-client#248]
Only happened since the Sierra upgrade. Am using the latest version (1.6.3). Followed instructions from this thread [https://github.com/prey/prey-node-client/issues/214](url) and removed then re-installed. No joy, so ran the patch @javo  posted at [http://prey.io/AwiskwLRETw](url). Still no joy. Result of running patch is thus: 
![prey patch](https://cloud.githubusercontent.com/assets/23451342/20262360/ce17509c-aa59-11e6-890b-ee2e216bfc9a.jpg)
Still getting this in Prey Control Panel 
![screen shot 2016-11-14 at 10 56 35](https://cloud.githubusercontent.com/assets/23451342/20262411/00e45dda-aa5a-11e6-8752-13dd5bb39c33.jpg)

Any suggestions appreciated.

Herb

**Comment by knappsimon** [comment]
I also have this with 1.6.4.

**Comment by lamuertepeluda** [comment]
Upgraded to macOS Sierra and using prey 1.6.5 (play reinstall). Running `prey check` I get this

```bash
     info Tue, 13 Dec 2016 13:57:26 GMT [actions] Starting action: geofencing
     info Tue, 13 Dec 2016 13:57:26 GMT [actions] Running: geofencing
     info Tue, 13 Dec 2016 13:57:26 GMT Plugin loaded: control-panel
     info Tue, 13 Dec 2016 13:57:26 GMT 1 plugins loaded with 0 errors.
     info Tue, 13 Dec 2016 13:57:26 GMT Initialized.
     info Tue, 13 Dec 2016 13:57:26 GMT [triggers] Watching: connection, network, power
     info Tue, 13 Dec 2016 13:57:26 GMT [actions] Starting trigger: connection
     info Tue, 13 Dec 2016 13:57:26 GMT [actions] Running: connection
     info Tue, 13 Dec 2016 13:57:26 GMT [actions] Starting trigger: network
     info Tue, 13 Dec 2016 13:57:26 GMT [actions] Starting trigger: power
    error Tue, 13 Dec 2016 13:57:26 GMT Unable to initialize db for geofences: Error: SQLITE_READONLY: attempt to write a readonly database
     info Tue, 13 Dec 2016 13:57:26 GMT [actions] Running: network
     info Tue, 13 Dec 2016 13:57:26 GMT [actions] Running: power
 critical Tue, 13 Dec 2016 13:57:26 GMT UNCAUGHT EXCEPTION: logger.err is not a function
     info Tue, 13 Dec 2016 13:57:27 GMT [long-polling] Got 1 commands.
     info Tue, 13 Dec 2016 13:57:30 GMT [reports] Gathering status report.
    error Tue, 13 Dec 2016 13:57:30 GMT [reports] Unable to get battery_status: No battery found.
     info Tue, 13 Dec 2016 13:57:31 GMT Gracefully shutting down. Will self-destruct in 5 secs.
     info Tue, 13 Dec 2016 13:57:31 GMT [actions] Stopping: geofencing
     info Tue, 13 Dec 2016 13:57:31 GMT [actions] Stopping: connection
     info Tue, 13 Dec 2016 13:57:31 GMT [actions] Stopping: network
     info Tue, 13 Dec 2016 13:57:31 GMT [actions] Stopping: power
     info Tue, 13 Dec 2016 13:57:31 GMT [hooks] Unregistering hooks.
     info Tue, 13 Dec 2016 13:57:31 GMT [actions] Stopping: connection
     info Tue, 13 Dec 2016 13:57:31 GMT [actions] Stopping: network
     info Tue, 13 Dec 2016 13:57:31 GMT [actions] Stopping: power
     info Tue, 13 Dec 2016 13:57:31 GMT Shutdown complete. Have a jolly good day sir.
```

I don't know if this is related/helpful

**Comment by javo** [comment]
Hi @lamuertepeluda, try running this command in your terminal `sudo chmod 755 /etc/prey/commands.db`, then `sudo pkill -f prx`. Let me know how it goes :)

**Comment by lamuertepeluda** [comment]
@javo error solved, but once I click Ctrl+c, the daemon shuts off... Am I missing something?

**Comment by HerbSomersal** [comment]
Can anyone throw some light on the issue I started the thread with please? Issue still outstanding.

**Comment by javo** [comment]
@HerbSomersal, please try uninstalling prey completely running `sudo /usr/local/lib/prey/current/bin/prey config hooks pre_uninstall && sudo rm -rf /usr/local/lib/prey /var/log/prey.log /etc/prey` then download the new version from https://github.com/prey/prey-node-client/releases/download/v1.6.5/prey-mac-1.6.5-x64.pkg and install it. If that doesnt work let me know please.

**Comment by javo** [comment]
@lamuertepeluda, run the daemon in the background using `sudo launchctl load /Library/LaunchDaemons/com.prey.agent.plist`

**Comment by HerbSomersal** [comment]
@javo Still 268 miles away. 
![screen shot 2016-12-13 at 14 31 05](https://cloud.githubusercontent.com/assets/23451342/21144013/eea0b1e8-c140-11e6-8909-b7e090464cb9.jpg)

**Comment by javo** [comment]
Ok, could you send me your prey.log file? the file is in the /etc/prey folder.

**Comment by lamuertepeluda** [comment]
@javo thank you! This definitely solved my issues! 😃

**Comment by HerbSomersal** [comment]
@javo 
![screen shot 2016-12-13 at 14 38 49](https://cloud.githubusercontent.com/assets/23451342/21144263/e4b1089e-c141-11e6-9019-e9cad389d8ee.jpg)
No such log file in that folder

**Comment by javo** [comment]
Awesome @lamuertepeluda.

**Comment by javo** [comment]
Wow @HerbSomersal, my bad.. the file is in /var/log/prey.log, sorry. Could you also run `id -g prey` in your terminal?

**Comment by HerbSomersal** [comment]
![screen shot 2016-12-13 at 14 41 17](https://cloud.githubusercontent.com/assets/23451342/21144362/436e6692-c142-11e6-983d-b9c9e752060c.jpg)
id -g prey produces 80

**Comment by javo** [comment]
@HerbSomersal try running an action from the control panel please, like the alarm, if that works means the problem is with your location only. Tell me if that's working.

**Comment by HerbSomersal** [comment]
@javo Yes, sent & received a message.

**Comment by javo** [comment]
@HerbSomersal I have a question, are you connected through ethernet or wifi? If you are still having problems with the location try to connect using a wifi net or at least enable your computer to see the networks around. I hope that helps :) Let me know if you're having troubles again

**Comment by HerbSomersal** [comment]
@javo That was the location issue - connected via ethernet. Now using wifi
