### ISSUE TITLE
openSUSE Leap 42.2 invalid OS error message

### ISSUE THREAD

**Issue by fid509** [prey/prey-node-client#249]
I get this error when trying to authorize:

> Linking device...
> Error! Invalid os:  does not exist.

This is the output of lsb-release -a:

> LSB Version:    n/a
> Distributor ID: openSUSE project
> Description:    openSUSE Leap 42.2
> Release:        42.2
> Codename:       n/a

**Comment by fid509** [comment]
Still no news bout this after 3 months?

**Comment by fid509** [comment]
Hello! Somebody here?

**Comment by javo** [comment]
Hey! Sorry for the delay man, we already have openSUSE included in our distro list but for some reason is not working, we're checking that out now. I'll let you know when is ready.

**Comment by javo** [comment]
hi @fid509, the case of OpenSUSE has been a little tricky. I need you to make a modification in the client code to make sure if it works. You need to go to `usr/lib/prey/current/node_modules/linus/index.js`, in that file in the line 54 you have this line of code: `cb(null, name.toString().replace(' Linux', '');` I need you to add this: `.replace(' project', '')`. So, the line should be: `cb(null, name.toString().replace(' Linux', '').replace(' project', ''));`. Then save the file and run this command to reset the client: `sudo pkill -f prx`. That should work, please let me know if it's working or not or if you have any doubt.
Greetings.

**Comment by fid509** [comment]
Hello java. This solution works. My device has been added with success.
PS. the location on my system was /usr/share/prey/node_modules/linus/index.js

**Comment by javo** [comment]
Awesome @fid509, I'm gonna add that fix in the next client release.
Thank you for your help!
