### ISSUE TITLE
Can't install Prey on my MacBook Air

### ISSUE THREAD

**Issue by Porphyry** [prey/prey-node-client#267]
Hi There:

I’ve downloader and run the installer three times, but Prey won’t install on my MacBook Air. I’ve also installed it from within Preyproject.com, and it still doesn’t add. I never get the dialogue box at the end asking me if I want to set up as an existing user: rather it just tells me to go to prey project.com, but my device doesn’t show up. 

Can you recommend a solution?

**Comment by javo** [comment]
Hi @Porphyry, try running this command: `sudo /usr/local/lib/prey/current/bin/prey config gui`. Tell me if that works please

**Comment by Porphyry** [comment]
I tried that but it didn't seem to work either. I got the following response: 

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

Password:

**Comment by javo** [comment]
I believe you got that warning because your user doesn't have a password assigned, so you have to set one to run sudo commands. In this link you have the necessary information support.apple.com/kb/HT4103. Let me know if you need any help :)

**Comment by javo** [comment]
Now, if you have a password, when you get that response you just have to type it there.

**Comment by Porphyry** [comment]
When I use my password in terminal it again opens the dialogue box that says "Sweet! Your computer is now protected by Prey. To try it out or to start tracking it, please visit preyproject.com." But I have seen that box before, and when I visit preyproject my third device, the one I am trying to install, is not there.

**Comment by Porphyry** [comment]
Please disregard. It is working now.

**Comment by javo** [comment]
Great :)
