### ISSUE TITLE
Invalid os: Solus

### ISSUE THREAD

**Issue by geexican** [prey/prey-node-client#268]
Prey doesn't recognize Linux [Solus](https://solus-project.com/) when trying to install through npm, I receive the "invalid os" message 

```
LSB_VERSION=1.4
DISTRIB_ID=Solus
DISTRIB_DESCRIPTION="Solus"
DISTRIB_RELEASE=2017.01.01.0
DISTRIB_CODENAME=shannon
```

**Comment by javo** [comment]
Hi @geexican, just added Solus distro, you can try again now :)

**Comment by geexican** [comment]
@javo it worked, thanks so much for the speedy reply
