### ISSUE TITLE
Auto-updated repeatedly silently fails download, used 75GB in one day

### ISSUE THREAD

**Issue by alibosworth** [prey/prey-node-client#278]
This was happening every day, all day in the background repeatedly.  I realize that something may have messed up permissions on my computer but I don't understand how there isn't some failsafe built in to avoid it.

[prey.log.txt](https://github.com/prey/prey-node-client/files/847730/prey.log.txt)

**Comment by javo** [comment]
Wow! Thank you for let us know this huge issue @alibosworth. Like you say it should be a permissions problem, to fix it you just have to run `sudo chmod -R prey /usr/local/lib/prey` and then restart the client with `sudo pkill -f prx`. I'm gonna cover this case right away, thank you again!

**Comment by alibosworth** [comment]
No problem.  Also note that the log file seemed to be wiped out when it re-attempted downloads, not sure if that is the designed behaviour.

Ali

**Comment by alibosworth** [comment]
@javo `sudo chmod -R prey /usr/local/lib/prey` responds with `chmod: Invalid file mode: prey`, is the format of that command incorrect?

**Comment by javo** [comment]
Sorry @alibosworth, my bad, the command is `sudo chown -R prey /usr/local/lib/prey`.
