### ISSUE TITLE
Prey not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by ethanchewy** [prey/prey-node-client#285]
The installer says that prey is installed in my computer, but when I log into prey in the web portal there is, it says "Unable to reach device"

Here's the prey.log file for reference:
`  PREY 1.6.6 spreads its wings!
  Current time: Tue Mar 28 2017 17:43:01 GMT-0400 (EDT)
  Running with PID 566 as prey over Node.js v4.4.5 on a x64 linux system (undefined)

     info Tue, 28 Mar 2017 21:43:01 GMT [actions] Starting action: geofencing
     info Tue, 28 Mar 2017 21:43:01 GMT [actions] Running: geofencing
     info Tue, 28 Mar 2017 21:43:01 GMT Plugin loaded: control-panel
     info Tue, 28 Mar 2017 21:43:01 GMT 1 plugins loaded with 0 errors.
     info Tue, 28 Mar 2017 21:43:01 GMT Initialized.
     info Tue, 28 Mar 2017 21:43:01 GMT [triggers] Watching: connection, network, power
     info Tue, 28 Mar 2017 21:43:01 GMT [actions] Starting trigger: connection
     info Tue, 28 Mar 2017 21:43:01 GMT [actions] Running: connection
     info Tue, 28 Mar 2017 21:43:01 GMT [actions] Starting trigger: network
     info Tue, 28 Mar 2017 21:43:01 GMT [actions] Starting trigger: power
     info Tue, 28 Mar 2017 21:43:01 GMT [actions] Running: network
     info Tue, 28 Mar 2017 21:43:01 GMT [actions] Running: power
     warn Tue, 28 Mar 2017 21:43:01 GMT [control-panel] Unable to sync settings.
    error Tue, 28 Mar 2017 21:43:01 GMT Error: Geofences list is not an array
     info Tue, 28 Mar 2017 21:43:01 GMT [actions] Stopped: geofencing`

**Comment by OrDuan** [comment]
Check out my issue too:
https://github.com/prey/prey-node-client/issues/284
