### ISSUE TITLE
Cannot achieve Nirvana on Manjaro linux

### ISSUE THREAD

**Issue by kernitus** [prey/prey-node-client#330]
Trying to install npm prey on Manjaro Linux. I was promised the script would help me achieve nirvana. Running the command `sudo npm -g prey` returns this error:

`npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/tomas/decompress-zip.git /root/.npm/_cacache/tmp/git-clone-9936a98e
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-9936a98e': Permission denied
npm ERR!` 

`npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-03T08_32_50_396Z-debug.log`

Running this command without `sudo` gives an error suggesting to use an admin account

**Comment by janus-reith** [comment]
Did anyone investigate further?
