### ISSUE TITLE
Prey thinks my laptop is offline when I am on LAN connection with WiFi off

### ISSUE THREAD

**Issue by mattpr** [prey/prey-node-client#331]
mid 2012 Macbook Pro
OSX 10.10.5 (14F2511)
Prey version 1.7.1

Seems that prey doesn't know how to connect to the internet when wifi is off and I am connected via LAN.  After about a day of being "docked" I get an email from prey:

> [Prey] Your Device XXX seems to be offline, everything ok?

The email can be ignored, the bigger problem is that this implies that prey won't be able to talk to my device when it is connected by LAN instead of WiFi.

My dock is a thunderbolt dock with ethernet, so perhaps the issue is related to that.

```
$ ifconfig | grep -E "^en[0-9]"
en1: flags=8823<UP,BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
en6: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
```

**Comment by josepablocam** [comment]
+1, same issue here
