### ISSUE TITLE
Prey not working on MacOS High Sierra 10.13

### ISSUE THREAD

**Issue by maddog120** [prey/prey-node-client#333]
Hi, since upgrading to MacOS High Sierra Prey has been unable to locate my device.  Have tried uninstalling and re-installing Prey but this has not helped.

**Comment by javo** [comment]
Hi @maddog120 , try with the patch we've created to resolve this issue, you can download it from here http://help.preyproject.com/article/240-after-upgrading-my-mac-to-sierra-prey-stopped-working15. The definitive solution to this problem it's almost done.
Let me know how it goes :)

**Comment by llazzaro** [comment]
@javo thanks. The patch fixed the issue with high sierra

**Comment by javo** [comment]
Great @llazzaro,
For the new Prey version 1.7.2 there's a definitive fix for this problem so it doesn't happen again for the next macOS upgrade. You just have to check you have that client version and run this command once: `sudo /usr/local/lib/prey/current/bin/prey config hooks set_watcher` and that's it :)
