### ISSUE TITLE
Main distros repository

### ISSUE THREAD

**Issue by mhalano** [prey/prey-node-client#36]
I think it is a good idea create repositories for main distros (Debian/Ubuntu and Fedora/Red Hat). This idea is to allow auto-update via apt and yum.

**Comment by LinuxOnTheDesktop** [comment]
I came here to ask for a PPA, but I read above about the auto-updating. Should the ability of the program to auto-update be made prominent, somehow? Also (if I may ask another question): is there a simple way of checking that the auto-update is working?
