### ISSUE TITLE
Installer fails on Linux Mint

### ISSUE THREAD

**Issue by jamzi** [prey/prey-node-client#413]
OS: Linux Mint 19
Prey version: 1.8.2

Tried installing .deb package, getting **"Your firefox profile cannot be loaded it may be missing or inaccessible"**. Weird, has Prey node client some hard dependency on Firefox or is this just how it works on Linux?

Tried some solutions with deleting Firefox profile file, didn't help. Also changing permissions on mozilla or firefox folders didn't work.

Any ideas?

**Comment by mef** [comment]
Also happens with debian 9 when installing Prey 1.8.3, even after setting chromium as the default browser.

**Comment by javo** [comment]
Hi, when Prey installation it's done the client opens a web configurator on the browser, seems there's an issue with Firefox profiles, I'm gonna review it.
For now you can set up your device using this command: `sudo /usr/lib/prey/current/bin/prey config gui`
