### ISSUE TITLE
Windows (64bit) installer has multiple problems

### ISSUE THREAD

**Issue by mgrandi** [prey/prey-node-client#438]
1: It seems that the installer uses the default path of `C:\Windows\Prey`. Why is this the installation directory? The correct place should be `C:\Program Files` (or whatever folder is appropriate for the language of windows and the 64/32 bit version of the program)

2: it seems that if you change the installation directory to any other folder other than `C:\Windows\Prey`, the installer fails.

log file: [prey-install.log](https://github.com/prey/prey-node-client/files/3607820/prey-install.log)

3: The installer does not correctly add an entry to <wherever place> windows expects when installing, so that a uninstall entry appears in the add/remove programs pane of settings. A user shouldn't have to look at a help article (https://help.preyproject.com/article/190-how-to-uninstall-prey) to figure out how to uninstall the application

Screenshot:

<img width="940" alt="prey installer not creating entry" src="https://user-images.githubusercontent.com/802786/64828400-1a470100-d57d-11e9-8941-2924e02eefad.png">

I don't see the script to generate the installer in the source code for this project so I cannot make a pull request to fix it

**Comment by JonnyTech** [comment]
1: Prey should be installed to a non-obvious folder for the reason of stealth

2: I cannot replicate this. What path are you trying to install to? Do you have write access to that folder? Can you try with latest release.

3: Again, for stealth reasons, it should not be easy to identify that Prey is installed or to uninstall on potentially stolen devices

**Comment by mgrandi** [comment]
sorry for the delayed response

i mean, if the goal is to not be obvious, why install to a folder called "Prey"? 

but i was just trying to install to a different directory, if prey does not support that then the installer shouldn't ask.

As requested, i ran it with the latest version, `prey-windows-1.9.4-x64.exe` (sha256 hash `7C9E682DFE137E8840F96E66B61BD49EAA27B225D49FA26AEEC93203424D535B` , still fails

the installer asks for admin privileges so it should have write access anywhere , but i also tried right clicking -> run as administrator and still same result

log:

[prey-install.log](https://github.com/prey/prey-node-client/files/4659556/prey-install.log)
