### ISSUE TITLE
Can't use prey on Manjaro Linux 

### ISSUE THREAD

**Issue by ninovolador** [prey/prey-node-client#45]
Hi, and sorry the bad english
Downloaded the prey node client 1.2.7 version via NPM. First GUI doesn't open, so i chose CLI option. When i configure my account:
```
Do you already have a Prey account? 
 - yes/no: [yes] 
Well hello old friend!
Please type your account's email address. 
 - email: myactualemail@mail.com
Well played. Now enter your password. 
 - pass: **********
Credentials verified.
Linking device...
Error! Invalid os:  does not exist.
```
Then i start prey:
``` bash
PREY 1.2.7 spreads its wings!
Current time: Sat Oct 04 2014 13:31:06 GMT-0300 (CLST)
Running under Node v0.10.32 with PID 8865 on a x64 linux system as username

info Sat, 04 Oct 2014 16:31:06 GMT [triggers] Watching: connection, network, power
info Sat, 04 Oct 2014 16:31:06 GMT [actions] Starting trigger: connection
info Sat, 04 Oct 2014 16:31:06 GMT [actions] Running: connection
info Sat, 04 Oct 2014 16:31:06 GMT [actions] Starting trigger: network
info Sat, 04 Oct 2014 16:31:06 GMT [actions] Starting trigger: power
info Sat, 04 Oct 2014 16:31:06 GMT [actions] Running: network
info Sat, 04 Oct 2014 16:31:06 GMT [actions] Running: power
info Sat, 04 Oct 2014 16:31:07 GMT [control-panel] Gathering device data...
info Sat, 04 Oct 2014 16:31:07 GMT [reports] Gathering specs report.
error Sat, 04 Oct 2014 16:31:07 GMT [reports] Unable to get storage_devices_list: TODO!
info Sat, 04 Oct 2014 16:31:07 GMT [reports] Report gathered: specs
error Sat, 04 Oct 2014 16:31:08 GMT [control-panel] Unable to register device: Invalid os:  does not exist.
error Sat, 04 Oct 2014 16:31:08 GMT Error: Invalid os:  does not exist.
info Sat, 04 Oct 2014 16:31:09 GMT 1 plugins loaded with 1 errors.
critical Sat, 04 Oct 2014 16:31:09 GMT UNCAUGHT EXCEPTION: Invalid os:  does not exist.
info Sat, 04 Oct 2014 16:31:14 GMT Gracefully shutting down. Will self-destruct in 5 secs.
info Sat, 04 Oct 2014 16:31:14 GMT [actions] Stopping: connection
info Sat, 04 Oct 2014 16:31:14 GMT [actions] Stopping: network
info Sat, 04 Oct 2014 16:31:14 GMT [actions] Stopping: power
info Sat, 04 Oct 2014 16:31:14 GMT [hooks] Unregistering hooks.
info Sat, 04 Oct 2014 16:31:19 GMT Time's up, shutdown forced. Have a jolly good day sir.
```

I think prey  doesn't recognize manjarolinux distro. Please make it so!! :pray:

**Comment by ninovolador** [comment]
Today an email was sent to me, about my notebook being registered on Prey. 

:) I supose this bug is fixed, thank you very much!!!!

**Comment by nieldk** [comment]
Please add the Jolla phone, It works quite well if I fake Debian release. But spits out wrong OS by default:
{~]$ lsb_release -ri
Distributor ID: Mer
Release:        0.2011

**Comment by shackra** [comment]
Man, this bug is ridiculous, you know how many GNU/Linux distros there exists, right?

In any case:

```
LSB Version:	n/a
Distributor ID:	Parabola
Description:	Parabola GNU/Linux-libre
Release:	rolling
Codename:	n/a
```

**Comment by lemavri** [comment]
@shackra This is actually not a bug, but a feature. We offer official support for the most widely used distros, and add other distros on a on-demand basis. You can expect Parabola GNU/Linux to be added by tomorrow.

**Comment by shackra** [comment]
Well, thank you.

Instead of `Error! Invalid os:  does not exist.` something more verbose should
be put in place thought


> El 19 de marzo de 2015 a las 03:29 PM Mauricio Schneider
> <notifications@github.com> escribió:
> 
> 
> @shackra This is actually not a bug, but a feature. We offer official support
> for the most widely used distros, and add other distros on a on-demand basis.
> You can expect Parabola GNU/Linux to be added by tomorrow.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/prey/prey-node-client/issues/45#issuecomment-83766591

--
Pax et bonum.
Jorge Araya Navarro.
ES: Diseñador Publicitario, Programador Python y colaborador en Parabola
GNU/Linux-libre
EN: Ads Designer, Python programmer and contributor Parabola GNU/Linux-libre
EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en
Parabola GNU/Linux-libre
https://es.gravatar.com/shackra

**Comment by lemavri** [comment]
Thanks, I agree with your suggestion. I'll make sure to replace the message.

**Comment by shackra** [comment]
@lemavri Parabola GNU/Linux isn't added, I still getting the error.

**Comment by lemavri** [comment]
@shackra I'm sorry for the delay. I'll fix it today.

**Comment by natsis** [comment]
LSB Version:	core-2.0-ia32:core-2.0-noarch:core-3.0-ia32:core-3.0-noarch:core-3.1-ia32:core-3.1-noarch:core-3.2-ia32:core-3.2-noarch:core-4.0-ia32:core-4.0-noarch:core-4.1-ia32:core-4.1-noarch:security-4.0-ia32:security-4.0-noarch:security-4.1-ia32:security-4.1-noarch
Distributor ID:	Kali
Description:	Kali GNU/Linux 1.1.0
Release:	1.1.0
Codename:	moto


Please add support for Kali

**Comment by rebeccaadams1232** [comment]
Hi, can you please add Redhat workstation?

# lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseWorkstation
Description:	Red Hat Enterprise Linux Workstation release 6.6 (Santiago)
Release:	6.6
Codename:	Santiago

**Comment by lemavri** [comment]
@natsis sorry for the delay. I just read your comment yesterday. We have added support for Kali, please feel free to try it out and let us know how it goes.

**Comment by mef** [comment]
Hi there, I know this issue is closed but I have the same problem on my linux distro (bunsenLabs, debian based)

The `Error! Invalid os:  does not exist.` error message shows up both on node.js cli and gui config.

````
$ lsb_release -a
No LSB modules are available.
Distributor ID:	BunsenLabs
Description:	BunsenLabs GNU/Linux 8.1 (Hydrogen)
Release:	8.1
Codename:	Hydrogen
````

````
$ cat /etc/issue
Debian GNU/Linux 8 \n \l
````

prey version: 1.4.2

It would perhaps be more sustainable to have a dynamic way of identifying linux distributions, instead of a hard-coded list...

**Comment by Chejone** [comment]
Hello, can you please add Jolla Tablet? :)

Mer release 0.2011 (Mer)
BUILD: Jolla-2.0.0.10-tbj-i486

[nemo@Jolla ~]$ lsb_release -a
LSB Version: :core-3.1-ia32:core-3.1-noarch:core-3.2-ia32:core-3.2-noarch:core-4.0-ia32:core-4.0-noarch:desktop-3.1-ia32:desktop-3.1-noarch:desktop-3.2-ia32:desktop-3.2-noarch:desktop-4.0-ia32:desktop-4.0-noarch
Distributor ID: #Thisfileiscopiedashw-release(analogoustoos-release)
Description: # This file is copied as hw-release (analogous to os-release)
Release: n/a
Codename: analogoustoos-release

[nemo@Jolla ~]$ lsb_release -ri
Distributor ID: #Thisfileiscopiedashw-release(analogoustoos-release)
Release: n/a

**Comment by WolfangAukang** [comment]
Hey guys, I can't install it on Korora. This is my lsb_release:

`Distributor ID:	Korora
Description:	Korora release 22 (Selina)
Release:	22
Codename:	Selina`

**Comment by PaveEvil** [comment]
Hi, can you please add Parrot

> No LSB modules are available.
> Distributor ID:	Parrot
> Description:	Parrot Security 3.4 - CyberFrigate
> Release:	3.4
> Codename:	cyberfrigate
>

**Comment by javo** [comment]
Hey @PaveEvil, we just add Parrot ![parrot](https://cloud.githubusercontent.com/assets/11738416/21644027/344db68e-d26a-11e6-8e9f-bf8cfdf2a06f.gif) try again please and let me know if it's working fine

**Comment by PaveEvil** [comment]
@javo All good
![screenshot at 2017-01-04 15-57-14](https://cloud.githubusercontent.com/assets/24901530/21645586/5bab7604-d29b-11e6-8366-c92c6e3a2076.png)

**Comment by matthew-nm** [comment]
Hi! Same issue for me, but I'm running OpenSUSE 42.2 Leap.

I found an .rpm someone had made before, ran the gui, and it recognized my system and even showed under "Devices" on the Prey web app, but it didn't actually function (it would never find my location or send a message). So I uninstalled that version of Prey and installed the node version via npm. Currently, the gui doesn't launch from the console, and the command-line account setup gives me the same error others have had in this thread.

If OpenSUSE could be added to the list of supported distros, that would be great!

**Comment by javo** [comment]
Hi @matthew-nm, we haven't fix this issue yet, for now please follow this instructions and it should be work fine https://github.com/prey/prey-node-client/issues/249#issuecomment-285051976.

**Comment by matthew-nm** [comment]
Thanks for the response, @javo!

I followed your directions in thread #249, except my `index.js` file was located in `/usr/local/lib/node_modules/prey/node_modules/linus/index.js`.

I was able to run through the command-line account setup (I needed to force it with `-f`), and it seemed that everything went well. However, my device is still not appearing on the web app. 

When I run `prey -p` I get ``error: option `-p, --path <path>' argument missing``. 

And when I run `prey -D` at first I got 
```
The Prey agent is running. Good job!
It has been live for 0.050 minutes, under process ID 19576.
To trigger actions or retrieve information, log in to your Prey account at https://preyproject.com
For additional configuration options, please run `prey config`.
```

but subsequent `prey -D` gave me
```
  ████████████████ ████████████████ ████████████████ ██            ██
  ██            ██ ██               ██            ██ ██            ██
  ██            ██ ██               ████████████████ ██            ██
  ██            ██ ██               ██               ██            ██
  ████████████████ ██               ████████████████ ████████████████
  ██                                                               ██
  ██                                                 ████████████████

  PREY 1.6.6 spreads its wings!
  Current time: Wed Mar 15 2017 10:11:18 GMT-0700 (PDT)
  Running with PID 19889 as matthew over Node.js v4.6.1 on a x64 linux system (undefined)

     info Wed, 15 Mar 2017 17:11:18 GMT [control-panel] Gathering device data...
 critical Wed, 15 Mar 2017 17:11:18 GMT UNCAUGHT EXCEPTION: Cannot read property 'replace' of undefined
    debug Wed, 15 Mar 2017 17:11:18 GMT TypeError: Cannot read property 'replace' of undefined
    at done (/usr/local/lib/node_modules/prey/node_modules/linus/index.js:54:52)
    at /usr/local/lib/node_modules/prey/node_modules/linus/index.js:63:5
    at /usr/local/lib/node_modules/prey/node_modules/linus/index.js:26:14
    at memorized (/usr/local/lib/node_modules/prey/node_modules/linus/node_modules/memorize/index.js:53:17)
    at get_distro_info (/usr/local/lib/node_modules/prey/node_modules/linus/index.js:24:3)
    at Object.exports.name [as get_os_name] (/usr/local/lib/node_modules/prey/node_modules/linus/index.js:57:3)
    at get_device_data (/usr/local/lib/node_modules/prey/lib/agent/plugins/control-panel/setup.js:51:16)
    at link_device (/usr/local/lib/node_modules/prey/lib/agent/plugins/control-panel/setup.js:13:3)
    at /usr/local/lib/node_modules/prey/lib/agent/plugins/control-panel/setup.js:135:9
    at Object.exports.set (/usr/local/lib/node_modules/prey/lib/agent/plugins/control-panel/api/keys.js:48:9)
     info Wed, 15 Mar 2017 17:11:18 GMT [reports] Gathering specs report.
    debug Wed, 15 Mar 2017 17:11:18 GMT [providers] Fetching processor_info
    debug Wed, 15 Mar 2017 17:11:18 GMT [reports] [4/5] Got processor_info
    debug Wed, 15 Mar 2017 17:11:18 GMT [providers] Fetching firmware_info
    debug Wed, 15 Mar 2017 17:11:18 GMT [providers] Fetching network_interfaces_list
    debug Wed, 15 Mar 2017 17:11:18 GMT [providers] Fetching ram_module_list
    debug Wed, 15 Mar 2017 17:11:18 GMT [providers] Fetching storage_devices_list
    error Wed, 15 Mar 2017 17:11:18 GMT [reports] Unable to get storage_devices_list: TODO!
    debug Wed, 15 Mar 2017 17:11:18 GMT [reports] [3/5] Got storage_devices_list
    debug Wed, 15 Mar 2017 17:11:18 GMT [reports] [2/5] Got firmware_info
    debug Wed, 15 Mar 2017 17:11:18 GMT [reports] [1/5] Got network_interfaces_list
    debug Wed, 15 Mar 2017 17:11:18 GMT [reports] [0/5] Got ram_module_list
     info Wed, 15 Mar 2017 17:11:18 GMT [reports] Report gathered: specs
     info Wed, 15 Mar 2017 17:11:23 GMT Gracefully shutting down. Will self-destruct in 5 secs.
    debug Wed, 15 Mar 2017 17:11:23 GMT Unloading plugins.
    debug Wed, 15 Mar 2017 17:11:23 GMT Stopping actions.
    debug Wed, 15 Mar 2017 17:11:23 GMT Unloading hooks.
     info Wed, 15 Mar 2017 17:11:23 GMT [hooks] Unregistering hooks.
    debug Wed, 15 Mar 2017 17:11:23 GMT Canceling reports.
    debug Wed, 15 Mar 2017 17:11:23 GMT Unwatching triggers.
    debug Wed, 15 Mar 2017 17:11:23 GMT Cleaning up temporary files.
     info Wed, 15 Mar 2017 17:11:28 GMT Time's up, shutdown forced. Have a jolly good day sir.
```

**Comment by javo** [comment]
Hmmm ok, you have an error when you're running the client, that's why your device isn't appearing.
Try uninstalling the npm version and install prey using the .deb package. After the install is done do what it's says in the thread i gave you.
Let me know how it goes :)

**Comment by matthew-nm** [comment]
Well, OpenSUSE uses the Redhat package system and not Debian, so I can't install .deb packages directly. The next best thing to do is install it from source, but I don't know how to do that. Is the source available? If so, I'm sure I can figure it out.

**Comment by ricqas** [comment]
Hello
I get the message os does not exist

Distributor ID:	antiX
Release:	17.2.1

Is there anyway to add this?
Does this matter with the api key?

**Comment by javo** [comment]
Hi @ricqas, I made the request to add antiX into our distro list, should be available soon, I'll let you know :)

**Comment by ricqas** [comment]
Hello 
Will this work on all antix distros any version? Also were you able to add?

Thanks

**Comment by javo** [comment]
Hi, antix distro is already added, could you try again @ricqas ? Should work with every version

**Comment by brokencog** [comment]
Hello, old thread here, but I'm wondering if Slackware could be added to the "accepted" distros.  I can manually tweak lsb_release output to "Ubuntu and prey will accept that, but ... that doesn't seem right.  Slackware doesn't have lsb_release by default, however the file /etc/slackware-version always exists with OS name and version number.

Anyway, hope this can be accomodated.
