### ISSUE TITLE
Monterey bugs

### ISSUE THREAD

**Issue by paxperscientiam** [prey/prey-node-client#525]
PreyProject has caused my mac's builtin camera to enable every 10 seconds (judging by the light).

Steps I took (not sure if reproducible)
* Installed preyproject from the website using the installer onto a fresh machine.
* Marked as missing on website.
* I then went through the process of installing certificate for extra features; that worked according to Apple and prey website.
* Noticed that reports weren't being generated on site.
* Marked CPU as found.

Steps I've taken to address:
* I tried restarting both owl and prey, but that had no effect.
* Gathered Log report (see below). Seems to indicate a problem phoning home, followed by code exception.
* Tried disabling Mozilla VPN (no apparent effect)
* Tried toggling missing status on and off on website (no effect)

Assessment:
Prey appears to have received the signal that indicates that the linked device is missing. However, thereafter, it was not able to phone home, which probably explains why there aren't any reports listed on the website.

Please help!

**EDIT**
The camera is now active continuously (again, going by light). Also, there should be a comma before "sir" re " Have a jolly good day sir".

**EDIT**
Just an FYI for anyone else who might have this issue, stopping the agents works re camera usage.

**System**
<img width="357" alt="Screen Shot 2021-11-15 at 12 18 30 PM" src="https://user-images.githubusercontent.com/7539871/141825537-b3eba882-4d28-4f91-9d42-01c3724a26de.png">

**Log**

>  ████████████████ ████████████████ ████████████████ ██            ██
>   ██            ██ ██               ██            ██ ██            ██
>   ██            ██ ██               ████████████████ ██            ██
>   ██            ██ ██               ██               ██            ██
>   ████████████████ ██               ████████████████ ████████████████
>   ██                                                               ██
>   ██                                                 ████████████████
> 
>   PREY 1.9.13 spreads its wings!
>   Current time: Mon Nov 15 2021 12:26:18 GMT-0500 (Eastern Standard Time)
>   Running with PID 4947 as prey over Node.js v14.16.0 on a x64 mac system (12.0.1)
> 
>      info Mon, 15 Nov 2021 17:26:18 GMT Plugin loaded: control-panel
>      info Mon, 15 Nov 2021 17:26:18 GMT 1 plugins loaded with 0 errors.
>      info Mon, 15 Nov 2021 17:26:18 GMT Initialized.
>      info Mon, 15 Nov 2021 17:26:18 GMT [triggers] Watching: connection, control-zones, hostname, location, network, power, status
>      info Mon, 15 Nov 2021 17:26:18 GMT [actions] Starting trigger: connection
>      info Mon, 15 Nov 2021 17:26:18 GMT [actions] Running: connection
>      info Mon, 15 Nov 2021 17:26:18 GMT [actions] Starting trigger: control-zones
>      info Mon, 15 Nov 2021 17:26:18 GMT [actions] Running: control-zones
>      info Mon, 15 Nov 2021 17:26:18 GMT [actions] Starting trigger: hostname
>      info Mon, 15 Nov 2021 17:26:18 GMT [actions] Starting trigger: location
>      info Mon, 15 Nov 2021 17:26:18 GMT [actions] Running: location
>      info Mon, 15 Nov 2021 17:26:18 GMT [actions] Starting trigger: network
>      info Mon, 15 Nov 2021 17:26:18 GMT [actions] Starting trigger: power
>      info Mon, 15 Nov 2021 17:26:18 GMT [actions] Starting trigger: status
>      info Mon, 15 Nov 2021 17:26:18 GMT [actions] Running: status
>      info Mon, 15 Nov 2021 17:26:18 GMT [hooks] Hook triggered: providers_ready
>      warn Mon, 15 Nov 2021 17:26:18 GMT Relaunching 1 commands previously in execution.
>      info Mon, 15 Nov 2021 17:26:18 GMT [hooks] Hook triggered: command
>      info Mon, 15 Nov 2021 17:26:18 GMT [reports] Gathering stolen report.
>      info Mon, 15 Nov 2021 17:26:18 GMT [hooks] Hook triggered: get_location
>      info Mon, 15 Nov 2021 17:26:18 GMT [providers] access_points_list already in progress.
>      info Mon, 15 Nov 2021 17:26:18 GMT [reports] Queuing stolen report every 10 minutes.
>     error Mon, 15 Nov 2021 17:26:18 GMT [reports] Unable to get gateway_ip: No active network interface found.
>  critical Mon, 15 Nov 2021 17:26:18 GMT UNCAUGHT EXCEPTION: Cannot read property 'trim' of undefined
>      info Mon, 15 Nov 2021 17:26:18 GMT [actions] Running: power
>      info Mon, 15 Nov 2021 17:26:19 GMT [hooks] Hook triggered: connected
>  critical Mon, 15 Nov 2021 17:26:19 GMT UNCAUGHT EXCEPTION: Cannot read property 'trim' of undefined
>      info Mon, 15 Nov 2021 17:26:19 GMT [actions] Running: network
>      info Mon, 15 Nov 2021 17:26:19 GMT Gracefully shutting down. Will self-destruct in 5 secs.
>      info Mon, 15 Nov 2021 17:26:19 GMT [actions] Stopping: connection
>      info Mon, 15 Nov 2021 17:26:19 GMT [actions] Stopping: control-zones
>      info Mon, 15 Nov 2021 17:26:19 GMT [actions] Stopping: location
>      info Mon, 15 Nov 2021 17:26:19 GMT [actions] Stopping: status
>      info Mon, 15 Nov 2021 17:26:19 GMT [actions] Stopping: power
>      info Mon, 15 Nov 2021 17:26:19 GMT [actions] Stopping: network
>      info Mon, 15 Nov 2021 17:26:19 GMT [hooks] Unregistering hooks.
>      warn Mon, 15 Nov 2021 17:26:19 GMT [reports] Canceling stolen report.
>      info Mon, 15 Nov 2021 17:26:19 GMT [actions] Stopping: connection
>      info Mon, 15 Nov 2021 17:26:19 GMT [actions] Stopping: control-zones
>      info Mon, 15 Nov 2021 17:26:19 GMT [actions] Stopping: location
>      info Mon, 15 Nov 2021 17:26:19 GMT [actions] Stopping: status
>      info Mon, 15 Nov 2021 17:26:19 GMT [actions] Stopping: power
>      info Mon, 15 Nov 2021 17:26:19 GMT [actions] Stopping: network
>      info Mon, 15 Nov 2021 17:26:19 GMT Shutdown complete. Have a jolly good day sir.
>

**Comment by JohaoRosasRosillo** [comment]
Hello @paxperscientiam ! This week we will launch a new release that will solve the problems that are occurring in Monterrey, we’re sorry about the inconvenience,
Regards

**Comment by paxperscientiam** [comment]
hi @JohaoRosasRosillo , no worries. thanks for the update!

**Comment by paxperscientiam** [comment]
After upgrading to version 1.9.14, the issue with the camera appears to be fixed. Indeed, reports are now being generated and dispatched to prey servers.

**Comment by patriciojofre** [comment]
🙌
