### ISSUE TITLE
Prey Location Off over 300 miles

### ISSUE THREAD

**Issue by ESDAC** [prey/prey-node-client#543]
Prey has device located in Texas on Spencer Road and it is actually located in New Jersey.  All location software is correct on device, but prey is incorrect. Please advise.

**Comment by JohaoRosasRosillo** [comment]
Hello @ESDAC  , we have some questions
What operating system do you use?
How long has this happened to you?
Send a picture of your Wi-Fi networks.
Run the following commands and send the result

Windows
netsh wlan show all
Mac
/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -s


Thanks!

**Comment by ESDAC** [comment]
windows 11 64 bit
past month on new laptop

=======================================================================
============================== SHOW DRIVERS ===========================
=======================================================================


Interface name: Wi-Fi

    Driver                    : Intel(R) Wi-Fi 6 AX201 160MHz
    Vendor                    : Intel Corporation
    Provider                  : Intel
    Date                      : 5/27/2021
    Version                   : 22.60.0.6
    INF file                  : oem254.inf
    Type                      : Native Wi-Fi Driver
    Radio types supported     : 802.11b 802.11g 802.11n 802.11a 802.11ac 802.11ax
    FIPS 140-2 mode supported : Yes
    802.11w Management Frame Protection supported : Yes
    Hosted network supported  : No
    Authentication and cipher supported in infrastructure mode:
                                Open            None
                                Open            WEP-40bit
                                Open            WEP-104bit
                                Open            WEP
                                WPA-Enterprise  TKIP
                                WPA-Enterprise  CCMP
                                WPA-Personal    TKIP
                                WPA-Personal    CCMP
                                WPA2-Enterprise TKIP
                                WPA2-Enterprise CCMP
                                WPA2-Personal   TKIP
                                WPA2-Personal   CCMP
                                Open            Vendor defined
                                WPA3-Personal   CCMP
                                Vendor defined  Vendor defined
                                WPA3-Enterprise 192 BitsGCMP-256
                                OWE             CCMP
    IHV service present       : Yes
    IHV adapter OUI           : [00 00 00], type: [00]
    IHV extensibility DLL path: C:\windows\system32\IntelIHVRouter08.dll
    IHV UI extensibility ClSID: {00000000-0000-0000-0000-000000000000}
    IHV diagnostics CLSID     : {00000000-0000-0000-0000-000000000000}
    Wireless Display Supported: Yes (Graphics Driver: Yes, Wi-Fi Driver: Yes)


=======================================================================
============================= SHOW INTERFACES =========================
=======================================================================


There is 1 interface on the system:

    Name                   : Wi-Fi
    Description            : Intel(R) Wi-Fi 6 AX201 160MHz
    GUID                   : 397c2c3b-d1c7-4841-b00b-62f321319345
    Physical address       : 8c:1d:96:c2:b9:92
    Interface type         : Primary
    State                  : connected
    SSID                   : TYNESFAMILY
    BSSID                  : 5c:7d:7d:2c:83:57
    Network type           : Infrastructure
    Radio type             : 802.11ax
    Authentication         : WPA2-Personal
    Cipher                 : CCMP
    Connection mode        : Auto Connect
    Band                   : 5 GHz
    Channel                : 157
    Receive rate (Mbps)    : 1134
    Transmit rate (Mbps)   : 721
    Signal                 : 83%
    Profile                : TYNESFAMILY

    Hosted network status  : Not available


=======================================================================
=========================== SHOW HOSTED NETWORK =======================
=======================================================================


Hosted network settings
-----------------------
    Mode                   : Allowed
    Settings               : <Not configured>

Hosted network status
---------------------
    Status                 : Not available


=======================================================================
============================= SHOW SETTINGS ===========================
=======================================================================


Wireless LAN settings
---------------------
    Show blocked networks in visible network list: No

    Only use GP profiles on GP-configured networks: No

    Hosted network mode allowed in WLAN service: Yes

    Allow shared user credentials for network authentication: Yes

    Block period: Not Configured.

    Auto configuration logic is enabled on interface "Wi-Fi"
    MAC randomization disabled on interface Wi-Fi


=======================================================================
============================== SHOW FILTERS ===========================
=======================================================================


Allow list on the system (group policy)
---------------------------------------
    <None>

Allow list on the system (user)
-------------------------------
    <None>

Block list on the system (group policy)
---------------------------------------
    <None>

Block list on the system (user)
-------------------------------
    <None>


=======================================================================
=========================== SHOW CREATEALLUSER ========================
=======================================================================


Everyone is allowed to create all user profiles.


=======================================================================
============================= SHOW PROFILES ===========================
=======================================================================


Profiles on interface Wi-Fi:

Group policy profiles (read only)
---------------------------------
    <None>

User profiles
-------------
    All User Profile     : TYNESFAMILY
    All User Profile     : TYNESFAMILY_5G


=======================================================================
========================== SHOW PROFILES NAME=* =======================
=======================================================================


Profile TYNESFAMILY on interface Wi-Fi:
=======================================================================

Applied: All User Profile

Profile information
-------------------
    Version                : 1
    Type                   : Wireless LAN
    Name                   : TYNESFAMILY
    Control options        :
        Connection mode    : Connect automatically
        Network broadcast  : Connect only if this network is broadcasting
        AutoSwitch         : Do not switch to other networks
        MAC Randomization  : Disabled

Connectivity settings
---------------------
    Number of SSIDs        : 1
    SSID name              : "TYNESFAMILY"
    Network type           : Infrastructure
    Radio type             : [ Any Radio Type ]
    Vendor extension          : Not present

Security settings
-----------------
    Authentication         : WPA2-Personal
    Cipher                 : CCMP
    Authentication         : WPA2-Personal
    Cipher                 : GCMP
    Security key           : Present

Cost settings
-------------
    Cost                   : Unrestricted
    Congested              : No
    Approaching Data Limit : No
    Over Data Limit        : No
    Roaming                : No
    Cost Source            : Default


Profile TYNESFAMILY_5G on interface Wi-Fi:
=======================================================================

Applied: All User Profile

Profile information
-------------------
    Version                : 1
    Type                   : Wireless LAN
    Name                   : TYNESFAMILY_5G
    Control options        :
        Connection mode    : Connect automatically
        Network broadcast  : Connect only if this network is broadcasting
        AutoSwitch         : Do not switch to other networks
        MAC Randomization  : Disabled

Connectivity settings
---------------------
    Number of SSIDs        : 1
    SSID name              : "TYNESFAMILY_5G"
    Network type           : Infrastructure
    Radio type             : [ Any Radio Type ]
    Vendor extension          : Not present

Security settings
-----------------
    Authentication         : WPA2-Personal
    Cipher                 : CCMP
    Authentication         : WPA2-Personal
    Cipher                 : GCMP
    Security key           : Present

Cost settings
-------------
    Cost                   : Unrestricted
    Congested              : No
    Approaching Data Limit : No
    Over Data Limit        : No
    Roaming                : No
    Cost Source            : Default


=======================================================================
======================= SHOW NETWORKS MODE=BSSID ======================
=======================================================================


Interface name : Wi-Fi
There are 1 networks currently visible.

SSID 1 : TYNESFAMILY
    Network type            : Infrastructure
    Authentication          : WPA2-Personal
    Encryption              : CCMP
    BSSID 1                 : 5c:7d:7d:2c:83:57
         Signal             : 83%
         Radio type         : 802.11ax
         Band               : 5 GHz
         Channel            : 157
         Bss Load:
             Connected Stations:         3
             Channel Utilization:        28 (10 %)
             Medium Available Capacity:  0 (0 us/s)
         Basic rates (Mbps) : 6 12 24
         Other rates (Mbps) : 9 18 36 48 54


=======================================================================
======================= SHOW INTERFACE CAPABILITIES ===================
=======================================================================


Wireless System Capabilities
----------------------------
    Number of antennas connected to the 802.11 radio (value not available)
    Max number of channels the device can operate on, simultaneously (value not available)
    Co-existence Support                        : Unknown


Wireless Device Capabilities
----------------------------

Interface name: Wi-Fi

    WDI Version (Windows)                       : 0.1.1.12
    WDI Version (IHV)                           : 0.1.1.9
    WiFiCx Version (IHV)                        : WiFiCx Interface Not Supported
    Firmware Version                            : 14.AD
    Station                                     : Supported
    Soft AP                                     : Not supported
    Network monitor mode                        : Not supported
    Wi-Fi Direct Device                         : Supported
    Wi-Fi Direct GO                             : Supported
    Wi-Fi Direct Client                         : Supported
    Protected Management Frames                 : Supported
    DOT11k neighbor report                      : Supported
    ANQP Service Information Discovery          : Supported
    Action Frame                                : Supported
    Diversity Antenna                           : Supported
    IBSS                                        : Not Supported
    Promiscuous Mode                            : Not Supported
    P2P Device Discovery                        : Supported
    P2P Service Name Discovery                  : Supported
    P2P Service Info Discovery                  : Not Supported
    P2P Background Discovery                    : Supported
    P2P GO on 5 GHz                             : Supported
    ASP 2.0 Service Name Discovery              : Not Supported
    ASP 2.0 Service Information Discovery       : Not Supported
    IP Docking Capable                          : Not Supported
    FIPS                                        : Supported
    Instant Connect                             : Supported
    Dx Standby NLO                              : Supported
    Extended Channel Switch Announcement        : Supported
    Function Level Reset                        : Supported
    Platform Level Reset                        : Supported
    Bus Level Reset                             : Supported
    MAC Randomization                           : Supported
    Fast Transition                             : Supported
    MU-MIMO                                     : Supported
    Miracast Sink                               : Supported
    BSS Transition (802.11v)                    : Supported
    IHV Extensibility Module Configured         : Supported
    SAE Authentication                          : Supported
    SAE Hash-to-Element Authentication          : Not Supported
    WPA3 SUITE-B Authentication                 : Not Supported
    WPA3 SUITE-B FIPS Mode                      : Not Supported
    OWE Authentication                          : Supported
    FTM as Initiator                            : Not Supported
    MBO Support                                 : Supported
    Number of Tx Spatial Streams                : 2
    Number of Rx Spatial Streams                : 2
    Number of Concurrent Channels Supported     : 0
    P2P GO ports count                          : 1
    P2P Clients Port Count                      : 1
    P2P Max Mobile AP Clients                   : 10
    Max ANQP Service Advertisements Supported   : 0
    Maximum Number of Secondary STAs supported  : 0
    Co-existence Support                        : Wi-Fi performance is maintained

**Comment by ESDAC** [comment]
![image](https://user-images.githubusercontent.com/97417714/148871625-a2d6304a-a36d-4c39-a6f0-b223c83218e9.png)

**Comment by JohaoRosasRosillo** [comment]
I see that it only has a visible wifi network(**SHOW NETWORKS MODE=BSSID**), in order to obtain its location correctly you need to have at least three networks, is it possible that you can try connecting to another wifi network?

**Comment by ESDAC** [comment]
I am still having the same issue after connecting to another network.


C:\Users\ebene>netsh wlan show all
Wireless System Information Summary
(Time: 1/11/2022 9:47:34 PM Eastern Standard Time)


=======================================================================
============================== SHOW DRIVERS ===========================
=======================================================================


Interface name: Wi-Fi

    Driver                    : Intel(R) Wi-Fi 6 AX201 160MHz
    Vendor                    : Intel Corporation
    Provider                  : Intel
    Date                      : 5/27/2021
    Version                   : 22.60.0.6
    INF file                  : oem254.inf
    Type                      : Native Wi-Fi Driver
    Radio types supported     : 802.11b 802.11g 802.11n 802.11a 802.11ac
802.11ax
    FIPS 140-2 mode supported : Yes
    802.11w Management Frame Protection supported : Yes
    Hosted network supported  : No
    Authentication and cipher supported in infrastructure mode:
                                Open            None
                                Open            WEP-40bit
                                Open            WEP-104bit
                                Open            WEP
                                WPA-Enterprise  TKIP
                                WPA-Enterprise  CCMP
                                WPA-Personal    TKIP
                                WPA-Personal    CCMP
                                WPA2-Enterprise TKIP
                                WPA2-Enterprise CCMP
                                WPA2-Personal   TKIP
                                WPA2-Personal   CCMP
                                Open            Vendor defined
                                WPA3-Personal   CCMP
                                Vendor defined  Vendor defined
                                WPA3-Enterprise 192 BitsGCMP-256
                                OWE             CCMP
    IHV service present       : Yes
    IHV adapter OUI           : [00 00 00], type: [00]
    IHV extensibility DLL path: C:\windows\system32\IntelIHVRouter08.dll
    IHV UI extensibility ClSID: {00000000-0000-0000-0000-000000000000}
    IHV diagnostics CLSID     : {00000000-0000-0000-0000-000000000000}
    Wireless Display Supported: Yes (Graphics Driver: Yes, Wi-Fi Driver:
Yes)


=======================================================================
============================= SHOW INTERFACES =========================
=======================================================================


There is 1 interface on the system:

    Name                   : Wi-Fi
    Description            : Intel(R) Wi-Fi 6 AX201 160MHz
    GUID                   : 397c2c3b-d1c7-4841-b00b-62f321319345
    Physical address       : 8c:1d:96:c2:b9:92
    Interface type         : Primary
    State                  : connected
    SSID                   : TYNES_Guest
    BSSID                  : d4:5d:64:a0:88:59
    Network type           : Infrastructure
    Radio type             : 802.11ax
    Authentication         : WPA2-Personal
    Cipher                 : CCMP
    Connection mode        : Auto Connect
    Band                   : 2.4 GHz
    Channel                : 5
    Receive rate (Mbps)    : 287
    Transmit rate (Mbps)   : 258
    Signal                 : 93%
    Profile                : TYNES_Guest

    Hosted network status  : Not available


=======================================================================
=========================== SHOW HOSTED NETWORK =======================
=======================================================================


Hosted network settings
-----------------------
    Mode                   : Allowed
    Settings               : <Not configured>
C:\Users\ebene>
Hosted network status
C:\Users\ebene>------
    Status                 : Not available


=======================================================================
============================= SHOW SETTINGS ===========================
=======================================================================


Wireless LAN settings
---------------------
    Show blocked networks in visible network list: No

    Only use GP profiles on GP-configured networks: No

    Hosted network mode allowed in WLAN service: Yes

    Allow shared user credentials for network authentication: Yes

    Block period: Not Configured.

    Auto configuration logic is enabled on interface "Wi-Fi"
    MAC randomization disabled on interface Wi-Fi


=======================================================================
============================== SHOW FILTERS ===========================
=======================================================================


Allow list on the system (group policy)
---------------------------------------
    <None>

Allow list on the system (user)
-------------------------------
    <None>

Block list on the system (group policy)
---------------------------------------
    <None>

Block list on the system (user)
-------------------------------
    <None>


=======================================================================
=========================== SHOW CREATEALLUSER ========================
=======================================================================


Everyone is allowed to create all user profiles.


=======================================================================
============================= SHOW PROFILES ===========================
=======================================================================


Profiles on interface Wi-Fi:

Group policy profiles (read only)
---------------------------------
    <None>

User profiles
-------------
    All User Profile     : TYNES_Guest
    All User Profile     : TYNESFAMILY_5G
    All User Profile     : TYNESFAMILY


=======================================================================
========================== SHOW PROFILES NAME=* =======================
=======================================================================


Profile TYNES_Guest on interface Wi-Fi:
=======================================================================

Applied: All User Profile

Profile information
-------------------
    Version                : 1
    Type                   : Wireless LAN
    Name                   : TYNES_Guest
    Control options        :
        Connection mode    : Connect automatically
        Network broadcast  : Connect only if this network is broadcasting
        AutoSwitch         : Do not switch to other networks
        MAC Randomization  : Disabled

Connectivity settings
---------------------
    Number of SSIDs        : 1
    SSID name              : "TYNES_Guest"
    Network type           : Infrastructure
    Radio type             : [ Any Radio Type ]
    Vendor extension          : Not present

Security settings
-----------------
    Authentication         : WPA2-Personal
    Cipher                 : CCMP
    Authentication         : WPA2-Personal
    Cipher                 : GCMP
    Security key           : Present

Cost settings
-------------
    Cost                   : Unrestricted
    Congested              : No
    Approaching Data Limit : No
    Over Data Limit        : No
    Roaming                : No
    Cost Source            : Default


Profile TYNESFAMILY_5G on interface Wi-Fi:
=======================================================================

Applied: All User Profile

Profile information
-------------------
    Version                : 1
    Type                   : Wireless LAN
    Name                   : TYNESFAMILY_5G
    Control options        :
        Connection mode    : Connect automatically
        Network broadcast  : Connect only if this network is broadcasting
        AutoSwitch         : Do not switch to other networks
        MAC Randomization  : Disabled

Connectivity settings
---------------------
    Number of SSIDs        : 1
    SSID name              : "TYNESFAMILY_5G"
    Network type           : Infrastructure
    Radio type             : [ Any Radio Type ]
    Vendor extension          : Not present

Security settings
-----------------
    Authentication         : WPA2-Personal
    Cipher                 : CCMP
    Authentication         : WPA2-Personal
    Cipher                 : GCMP
    Security key           : Present

Cost settings
-------------
    Cost                   : Unrestricted
    Congested              : No
    Approaching Data Limit : No
    Over Data Limit        : No
    Roaming                : No
    Cost Source            : Default


Profile TYNESFAMILY on interface Wi-Fi:
=======================================================================

Applied: All User Profile

Profile information
-------------------
    Version                : 1
    Type                   : Wireless LAN
    Name                   : TYNESFAMILY
    Control options        :
        Connection mode    : Connect automatically
        Network broadcast  : Connect only if this network is broadcasting
        AutoSwitch         : Do not switch to other networks
        MAC Randomization  : Disabled

Connectivity settings
---------------------
    Number of SSIDs        : 1
    SSID name              : "TYNESFAMILY"
    Network type           : Infrastructure
    Radio type             : [ Any Radio Type ]
    Vendor extension          : Not present

Security settings
-----------------
    Authentication         : WPA2-Personal
    Cipher                 : CCMP
    Authentication         : WPA2-Personal
    Cipher                 : GCMP
    Security key           : Present

Cost settings
-------------
    Cost                   : Unrestricted
    Congested              : No
    Approaching Data Limit : No
    Over Data Limit        : No
    Roaming                : No
    Cost Source            : Default


=======================================================================
======================= SHOW NETWORKS MODE=BSSID ======================
=======================================================================


Interface name : Wi-Fi
There are 1 networks currently visible.

SSID 1 : TYNES_Guest
    Network type            : Infrastructure
    Authentication          : WPA2-Personal
    Encryption              : CCMP
    BSSID 1                 : d4:5d:64:a0:88:59
         Signal             : 93%
         Radio type         : 802.11ax
         Band               : 2.4 GHz
         Channel            : 5
         Bss Load:
             Connected Stations:         2
             Channel Utilization:        34 (13 %)
             Medium Available Capacity:  0 (0 us/s)
         Basic rates (Mbps) : 1 2 5.5 11
         Other rates (Mbps) : 6 9 12 18 24 36 48 54


=======================================================================
======================= SHOW INTERFACE CAPABILITIES ===================
=======================================================================


Wireless System Capabilities
----------------------------
    Number of antennas connected to the 802.11 radio (value not available)
    Max number of channels the device can operate on, simultaneously (value
not available)
    Co-existence Support                        : Unknown


Wireless Device Capabilities
----------------------------

Interface name: Wi-Fi

    WDI Version (Windows)                       : 0.1.1.12
    WDI Version (IHV)                           : 0.1.1.9
    WiFiCx Version (IHV)                        : WiFiCx Interface Not
Supported
    Firmware Version                            : 14.AD
    Station                                     : Supported
    Soft AP                                     : Not supported
    Network monitor mode                        : Not supported
    Wi-Fi Direct Device                         : Supported
    Wi-Fi Direct GO                             : Supported
    Wi-Fi Direct Client                         : Supported
    Protected Management Frames                 : Supported
    DOT11k neighbor report                      : Supported
    ANQP Service Information Discovery          : Supported
    Action Frame                                : Supported
    Diversity Antenna                           : Supported
    IBSS                                        : Not Supported
    Promiscuous Mode                            : Not Supported
    P2P Device Discovery                        : Supported
    P2P Service Name Discovery                  : Supported
    P2P Service Info Discovery                  : Not Supported
    P2P Background Discovery                    : Supported
    P2P GO on 5 GHz                             : Supported
    ASP 2.0 Service Name Discovery              : Not Supported
    ASP 2.0 Service Information Discovery       : Not Supported
    IP Docking Capable                          : Not Supported
    FIPS                                        : Supported
    Instant Connect                             : Supported
    Dx Standby NLO                              : Supported
    Extended Channel Switch Announcement        : Supported
    Function Level Reset                        : Supported
    Platform Level Reset                        : Supported
    Bus Level Reset                             : Supported
    MAC Randomization                           : Supported
    Fast Transition                             : Supported
    MU-MIMO                                     : Supported
    Miracast Sink                               : Supported
    BSS Transition (802.11v)                    : Supported
    IHV Extensibility Module Configured         : Supported
    SAE Authentication                          : Supported
    SAE Hash-to-Element Authentication          : Not Supported
    WPA3 SUITE-B Authentication                 : Not Supported
    WPA3 SUITE-B FIPS Mode                      : Not Supported
    OWE Authentication                          : Supported
    FTM as Initiator                            : Not Supported
    MBO Support                                 : Supported
    Number of Tx Spatial Streams                : 2
    Number of Rx Spatial Streams                : 2
    Number of Concurrent Channels Supported     : 0
    P2P GO ports count                          : 1
    P2P Clients Port Count                      : 1
    P2P Max Mobile AP Clients                   : 10
    Max ANQP Service Advertisements Supported   : 0
    Maximum Number of Secondary STAs supported  : 0
    Co-existence Support                        : Wi-Fi performance is
maintained



C:\Users\ebene>

**Comment by mhalano** [comment]
I'm having the same problem. I use Ubuntu and with Google Maps I get the right location, but using Prey I get the wrong location. And I have a few WiFi networks near me (I live in an apartment building). What informations do you need?
