### ISSUE TITLE
Missing "Advanced options" don't persist after system reboot (HS:advanced-missing-reboot)

### ISSUE THREAD

**Issue by fanuneza** [prey/prey-node-client#57]
![screenshot 2014-12-15 11 03 55](https://cloud.githubusercontent.com/assets/401279/5436919/597613d6-844a-11e4-8dc8-b58dbee628aa.png)

The options work fine, but since they're not saved on the servers they stop after a system reboot. They should persist.

**Comment by lemavri** [comment]
The status is now persisted in the panel, and since the client syncs with the server on boot, the missing status gets activated correctly after rebooting the device.

**Comment by fanuneza** [comment]
@lemavri: Is this already deployed or is it to-be-fixed on 1.3.7?
