### ISSUE TITLE
Prey client requires too much network resources (HS:node-busy-network)

### ISSUE THREAD

**Issue by fanuneza** [prey/prey-node-client#60]
According to a user:

> I have Prey checking my Windows 7 Desktop; on examining my network traffic this seems to be happening every 60 SECONDS which seems a bit excessive is there a way to change this. This is based on an executable node.exe which the internet says links to Prey. Total traffic each "ping" is about 3.7KB and at once a minute this makes it overall the second busiest application on my network only Firefox usage beats it.

---------------

Is that expected?

**Comment by fanuneza** [comment]
More feedback for this one.

![qwsrjue](https://cloud.githubusercontent.com/assets/401279/6113627/88cccc20-b077-11e4-8003-cc967587a45c.png)

**Comment by tomas** [comment]
This is caused because the PC is failing to perform the UPnP or NAT-PMP mapping. I would suggest the user to enable port mapping on his or her router. The long polling strategy we're currently testing should also decrease significantly the number of requests per minute on non mapped scenarios. 

@lemavri We'd probably need to replace the `setInterval` call in `plugins/control-panel/interval` for a `setTimeout` though, and call that method recursively once the request actually finishes.

**Comment by fanuneza** [comment]
I thought so, and replied accordingly. Simple math: Check-ins every 30 seconds mean 172,800 pings a day.

**Comment by pimientadaniel** [comment]
Suddenly 2 days ago Prey stopped to manage to got my PC position. At the same time I saw this node.exe process consuming abnormal CPU... I finished by relating the two events. I tried with Google Maps and it does manage to locate my PC by WIFI. I do see there is only my wifi with a clear signal at my place; is that the reason why Prey cannot locate anymore? Could it be a change of my ISP router parameters (which I cannot access)? Should I reload the Node,exe (or re-install the full application)  in case it got corrupted?

**Comment by javo** [comment]
Hi @pimientadaniel,
We got a problem with the 1.6.2 client version release. If the version you have installed doesn't update automatically to 1.6.3, you need to uninstall Prey and re-install it with the new version.
Please let me know how it goes.

**Comment by pimientadaniel** [comment]
Thanks for your fast and professional reaction. It took me some struggles :-) but it worked. For your information: 1) it would not download from Mozilla (I did was signed in) but it did from IE. 2) The installation first failed. I hand deleted as much as i could of what remained in directory after uninstall and the second shot worked. Thanks again.
