### ISSUE TITLE
Actions don't run on Prey 1.3.5 for Linux

### ISSUE THREAD

**Issue by Dominiquini** [prey/prey-node-client#61]
Actions are pushed from the user's Prey account, but are not run on the Linux (Ubuntu Precise) machine. Here's the log:

  PREY 1.3.5 spreads its wings!
  Current time: Sun Jan 04 2015 22:56:45 GMT-0200 (BRST)
  Running with PID 30287 as prey over Node.js v0.10.32 on a x64 linux system (3.8.10-gnu-1-generic)

     info Mon, 05 Jan 2015 00:56:46 GMT [triggers] Watching: connection, network, power
     info Mon, 05 Jan 2015 00:56:46 GMT [actions] Starting trigger: connection
     info Mon, 05 Jan 2015 00:56:46 GMT [actions] Running: connection
     info Mon, 05 Jan 2015 00:56:46 GMT [actions] Starting trigger: network
     info Mon, 05 Jan 2015 00:56:46 GMT [actions] Starting trigger: power
     info Mon, 05 Jan 2015 00:56:46 GMT [actions] Running: network
     info Mon, 05 Jan 2015 00:56:46 GMT [actions] Running: power
     warn Mon, 05 Jan 2015 00:56:47 GMT [control-panel] Not configured. Waiting for user input...
     info Mon, 05 Jan 2015 00:56:57 GMT [control-panel] Reloading config...
     info Mon, 05 Jan 2015 00:57:07 GMT [control-panel] Reloading config...
     info Mon, 05 Jan 2015 00:57:07 GMT [control-panel] Queueing check-ins every 20 minutes.
   notice Mon, 05 Jan 2015 00:57:07 GMT [control-panel] Checking for existing port mappings...
     info Mon, 05 Jan 2015 00:57:07 GMT [control-panel] No previously mapped ports found.
     info Mon, 05 Jan 2015 00:57:07 GMT [control-panel] Attempting to map external port 30313
     warn Mon, 05 Jan 2015 00:57:10 GMT [control-panel] Got 1 commands.
     info Mon, 05 Jan 2015 00:57:12 GMT [control-panel] Port 30313 mapped. Starting push handler.
     info Mon, 05 Jan 2015 00:57:13 GMT [control-panel] Updating notification ID...
   notice Mon, 05 Jan 2015 00:57:14 GMT [control-panel] Ready to receive push notifications.
     info Mon, 05 Jan 2015 00:57:15 GMT [reports] Gathering status report.
     info Mon, 05 Jan 2015 00:57:19 GMT [reports] Report gathered: status
     info Mon, 05 Jan 2015 00:57:19 GMT [control-panel] Posting data
     info Mon, 05 Jan 2015 00:57:20 GMT [control-panel] Got status 200 from server: OK
   notice Mon, 05 Jan 2015 00:57:50 GMT [control-panel] Got valid push request!
     warn Mon, 05 Jan 2015 00:57:50 GMT [control-panel] Got 1 commands.
     info Mon, 05 Jan 2015 00:57:50 GMT [actions] Starting action: alert
     info Mon, 05 Jan 2015 00:57:51 GMT [control-panel] Posting response
     info Mon, 05 Jan 2015 00:57:51 GMT [actions] Running: alert
     info Mon, 05 Jan 2015 00:57:51 GMT [actions] Stopped: alert
     info Mon, 05 Jan 2015 00:57:52 GMT [control-panel] Posting response

In the panel, everything seems to be working well. The computer appears as online, the actions are considered executed, the location is obtained, etc...

**Comment by boris** [comment]
Hi @Dominiquini, could you please try with another action, suck as Alarm and pase the output of your `/var/log/prey.log` file? You should hear a not-so-nice sound. This is to try to isolate the problem.

Thanks.

**Comment by mauricioschneider** [comment]
Hello @Dominiquini, 

Thanks for your report. We were able to reproduce the issue and are currently working on a fix.

**Comment by mauriciooo** [comment]
@Dominiquini version 1.3.6 will take care of this. It should be released today.
