### ISSUE TITLE
Webpage in português

### ISSUE THREAD

**Issue by jristz** [prey/prey-node-client#64]
Not sure if this is the correct place to report but I set the wepage of prey when you are login set someparts (many) to portuguese and other to english, leaving maybe 3 or 4 string in standard spainsh.

If the page have a transifex I can join and finish the translation (to standard spanisha dn latinamerican spanish) I'm coordinator and tranlator for Xfce, translator for bitbucker and Archlinux AUR page and package manager I have some exp.

**Comment by mauriciooo** [comment]
Hello @jristz,

Thanks for your feedback. We are indeed aware of the issue and we are working on it.

We appreciate your interest in helping us with the translations. Currently we are not crowdsourcing or outsourcing the translation process, as it's something our communications team handles personally.

**Comment by mauriciooo** [comment]
BTW, since this is related to our webpage, I'm going to close this.
