### ISSUE TITLE
No Prey package for Slitaz distribution of Linux

### ISSUE THREAD

**Issue by camilaburgos** [prey/prey-node-client#66]
##### According to a user:

>Is it possible to make a Prey package for Slitaz distribution?

>This is what Python shows when I try to use the ```prey-config.py``` to add a 
new device:

>** (process:2833): WARNING **: Trying to register gtype 'GMountMountFlags' 
as enum when in fact it is of type 'GFlags'

>** (process:2833): WARNING **: Trying to register gtype 'GDriveStartFlags' 
as enum when in fact it is of type 'GFlags'

>** (process:2833): WARNING **: Trying to register gtype 'GSocketMsgFlags' 
as enum when in fact it is of type 'GFlags'
Connection error. Response from server:

**Comment by lemavri** [comment]
This issue is being handle via helpscout. I will update it with further information later.
