### ISSUE TITLE
Prey 1.3.5 won't lock a dual-monitor setup (HS:node-dual-lock)

### ISSUE THREAD

**Issue by fanuneza** [prey/prey-node-client#70]
## Problem

Prey 1.3.5 won't lock both screens on Windows 8.1. I haven't been able to reproduce the bug, though.

## How it was detected.

It was reported by a customer, who [even recorded a video](https://prey.slack.com/files/fabian/F03BNL795/prey_ext_display_lock_test.mp4).

![vlcsnap-2015-01-13-10h16m59s74](https://cloud.githubusercontent.com/assets/401279/5721224/ad74e64a-9b0d-11e4-90c9-3a0f54800b06.png)

### System hardware

```
Motherboard: Gigabyte Z87X-UD5H-CF
CPU: Inter core i7 4770K 3.5GHz
RAM: Corsair Vengeance DDR3 32GB total
GPU: Nvidia GeForce GTX770 4GB
Display: dual monitors Samsung S27A350H HDMI connection (Primary) and AOC VGA/DVI connection
```

## Suggested solution

Force Prey to lock every available system screen.

## Resources

- https://secure.helpscout.net/conversation/64524117/11610/

**Comment by tomas** [comment]
We need more info about the guy's setup in order to reproduce the bug. Otherwise we won't be able to tell when we actually get it fixed.

**Comment by fanuneza** [comment]
Absolutely. I already asked the customer, and will update the issue as soon as he gets back to me.

**Comment by fanuneza** [comment]
Just added the system hardware to the issue.

**Comment by fanuneza** [comment]
Is there any information that you need, or any testing that the customer can do?

**Comment by lemavri** [comment]
The hardware information you added gives us a clue on how to reproduce the issue (HDMI + VGA). 

Are there more users reporting this?

**Comment by fanuneza** [comment]
No. A single customer is affected.

**Comment by fanuneza** [comment]
By the way, the customer said that he'd be glad to test in case you need that.

**Comment by camilaburgos** [comment]
A new customer is being affected by this issue.

- https://secure.helpscout.net/conversation/78122248/16566/
