### ISSUE TITLE
Silent installer not working v.1.10.11

### ISSUE THREAD

**Issue by mvught** [prey/prey-node-client#703]
curl -o /private/tmp/prey-mac-1.10.11-x64.pkg "https://downloads.preyproject.com/prey-client-releases/node-client/1.10.11/prey-mac-1.10.11-x64.pkg"

API_KEY="your key" sudo -E installer -pkg /private/tmp/prey-mac-1.10.11-x64.pkg -target /

But not showing in Server

**Comment by SoraKenji** [comment]
Hello there @mvught ! We don't usually respond to user issues with the program here, but you can write to help@preyproject.com and tell us about your problem there. Our support team will be glad to help you out!

You will receive an automate respond with FAQ, if that doesnt help you, you need to respond to that email and the support team will reach out to you.

**Comment by mvught** [comment]
Hello @SoraKenji  Thanks i will contact the support team!
