### ISSUE TITLE
login shell of prey user in ubuntu package better be /bin/false or /usr/sbin/nlogin

### ISSUE THREAD

**Issue by solsticedhiver** [prey/prey-node-client#74]
hi
in ubuntu package from prey site, a prey user and a prey group is created when the package is installed
but the login shell of the prey user is /bin/bash:

    $ grep prey /etc/passwd
    prey:x:999:999::/home/prey:/bin/bash

as a security measure, it could be better to use **/bin/false** or **/usr/sbin/nologin**
As I understand, *prey daemon* does not need a login shell (?)

**Comment by lemavri** [comment]
Hi @solsticedhiver, thanks for your feedback!
