### ISSUE TITLE
OS X's com.prey.agent.plist slows system shutdowns (HS:plist)

### ISSUE THREAD

**Issue by fanuneza** [prey/prey-node-client#75]
## Problem

According to a user,

> After installing prey to my macbook (Mavericks 10.9.5) I have started experiencing slow shutdowns. Further investigation pointed to the following setting in `/Library/LaunchDaemons/com.prey.agent.plist`. There there is parameter that sets exit timeout to the value 20. If I remove the plist file I have normal shutdown times, back to 2 seconds as before, and if I put it back the delay re-occurs. What exactly is that for and why the need to slow the shut own? Can I safely remove that specific parameter or set it to some lower value? 

The stable version was 1.3.4 at the time.

## How it was detected

User report.

## Suggested solution

Reduce the shutdown time, or confirm that the problem isn't caused by Prey.

## References

- https://secure.helpscout.net/conversation/63272644/10986/

**Comment by tomas** [comment]
20 is the default ExitTimeout for all OSX daemons. From the [original documentation](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man5/launchd.plist.5.html):

``` 
ExitTimeOut <integer>
     The amount of time launchd waits before sending a SIGKILL signal. The default value is 20 seconds. The
     value zero is interpreted as infinity.
```

So, basically, something's preventing a clean shutdown which causes `launchd` to wait 20 seconds before killing the process by force. I suspect that this may be related to 19607b8a374572c0795ad80a7ef37edc599c80ce so I would suggest the user to upgrade to the latest version before modifying anything. Also, we should try to reproduce the error before accepting this as as a valid bug.

**Comment by fanuneza** [comment]
Version 1.3.6 fixed the issue. I'll you know in case I get anything new.

**Comment by tomas** [comment]
Bravo.
