### ISSUE TITLE
Volume doesn't raise automatically when user triggers the alarm and the computer is muted  (HS:alarm-volume-bug)

### ISSUE THREAD

**Issue by camilaburgos** [prey/prey-node-client#78]
## Problem

When a Windows 7 laptop is muted and the user triggers the Alarm action, it will be started, but the volume won't be raised automatically, the computer will stay muted. 

## How it was detected

A free user reported it.

## Suggestions

To add the feature so Prey can raise the volume automatically when the device is muted and therefore, the alarm fulfills its purpose.

## Resources

- https://secure.helpscout.net/conversation/64989299/11840/

**Comment by lemavri** [comment]
The issue was not fixed. The commit was reverted because of license issues with the nircmd binary.
