### ISSUE TITLE
fs: missing callback Error: ENOENT, unlink '/etc/prey/prey.conf'

### ISSUE THREAD

**Issue by blackjid** [prey/prey-node-client#79]
After installing prey with `npm install -g prey` on my MBP osx 10.10, tried to configure it but I'm getting this...any idea?
```shell
prey config account setup
Error! Oops. Seems you don't have write permissions. Try running with sudo.
fs: missing callback Error: ENOENT, unlink '/etc/prey/prey.conf'
```

I also tried with sudo.

**Comment by lemavri** [comment]
You have to run it with ´sudo´:  ´sudo prey config account setup´, since the regular user doesn't have permissions to write the config file.

**Comment by blackjid** [comment]
I tried with sudo... I get the same error...

**Comment by lemavri** [comment]
Weird. For OS X I recommend you using [our installer](https://github.com/prey/prey-node-client/releases/download/v1.3.6/prey-mac-1.3.6-x64.pkg).

**Comment by blackjid** [comment]
Ok, I got it...
I installed prey without sudo, because I'm running nodenv and a don't wont node packages installed with sudo....

But I miss a message that sais that as I was running with an unprivileged user, I should run a script `sudo prey config hooks post_install`

After that I can run `sudo prey config account setup` and it seams to be working fine now.

**Comment by blackjid** [comment]
What's the difference between installing with npm and with the pkg installer?

**Comment by lemavri** [comment]
The installer allows to have multiple versions of Prey installer, while the npm package won't. Also, the pkg installer is a more straightforward process.

**Comment by pmichaeljones** [comment]
Can I reopen this issue? Trying to install Prey after upgrading to Catalina.

<img width="567" alt="Screen Shot 2019-11-28 at 8 23 26 AM" src="https://user-images.githubusercontent.com/6728265/69785463-671f9880-11b8-11ea-96be-3b90fd9dd5f8.png">
<img width="521" alt="Screen Shot 2019-11-28 at 8 23 10 AM" src="https://user-images.githubusercontent.com/6728265/69785464-671f9880-11b8-11ea-9bac-a2d3ea1b7826.png">
<img width="519" alt="Screen Shot 2019-11-28 at 8 22 56 AM" src="https://user-images.githubusercontent.com/6728265/69785465-671f9880-11b8-11ea-9cf7-94275b07bedb.png">
