### ISSUE TITLE
"Unable to get active_access_point: TODO!" message in the prey.log file (HS:unable-to-get-access-point)

### ISSUE THREAD

**Issue by camilaburgos** [prey/prey-node-client#92]
## Problem

This message appears sometimes in the log file, when the client or user doesn't get the geolocation in the reports after marking a device as "missing". There's no explanation for this yet. The client is connected to a Wi-Fi network and the photos and screenshots are arriving without problems. Maybe there is a program blocking the geo feature. 

![unable to get active access point error](https://cloud.githubusercontent.com/assets/10212992/6398437/61b837a4-bdca-11e4-9def-49704ad39c21.png)

## How it was detected

A client reported it.

## Suggestions

To check out if this error is coming from our end and fix it. If not, to determine what could be happening. 

## Resources

- https://secure.helpscout.net/conversation/74209021/15170/

**Comment by fanuneza** [comment]
This affects oh so many people.

**Comment by tomas** [comment]
It does. But only users of [older versions of Windows](https://github.com/prey/prey-node-client/blob/master/lib/agent/providers/network/windows.js#L31-L46) (os.release < 6.0).

**Comment by fanuneza** [comment]
@tomas: Is this related to the `Unable to get location: No access points found.` message when Wi-Fi is enabled, and HTML5-location services such as Google Maps can successfully locate devices?

**Comment by tomas** [comment]
Nopey. Getting the **active** access point is a different thing from the full list. If you look at the source code from the link in the previous comment (line 61), you'll see that access points list is covered for all Windows versions. 

It may be ocurring, though, that the commands that `get_access_points_list` depends on to get the list may be failing. But a totally different story.

**Comment by fanuneza** [comment]
Alright, then. Thanks. But regarding this issue, does it mean that we don't support Windows Vista and older?

**Comment by tomas** [comment]
Vista (6.0) should work. It's the older ones that are not currently supported. I'm +1 to fix this for XP/2000 even though Microsoft deprecated them officially, but I don't think it should be considered critical. Getting the full access points list works and so does geolocation.

**Comment by fanuneza** [comment]
The problem is that it doesn't. Location is terribly inaccurate, that's the source of the issue.

> This message appears sometimes in the log file, when the client or user doesn't get the geolocation in the reports after marking a device as "missing". There's no explanation for this yet. The client is connected to a Wi-Fi network and the photos and screenshots are arriving without problems. Maybe there is a program blocking the geo feature.

**Comment by camilaburgos** [comment]
Windows 7 and Windows 8.1 users are reporting this issue too.
