### ISSUE TITLE
Please add distro  to known OS's

### ISSUE THREAD

**Issue by nieldk** [prey/prey-node-client#94]
Please add the Jolla phone, It works quite well if I fake Debian release. But spits out wrong OS by default:
{~]$ lsb_release -ri
Distributor ID: Mer
Release: 0.2011

**Comment by lemavri** [comment]
Hello @nieldk,

Not long ago we were contacted by the Jolla phone guys because they were porting our Android app to Sailfish OS. Does the Jolla phone has some sort of app store? If so, have you checked in there for the Prey app?

**Comment by nieldk** [comment]
I am aware that Jolla is working on a solution for antitheft. Possibly Prey. It is ~ a year ago I first started working on Prey for the Jolla phone. At the same time one of the Jolla engineers announced they were also working on a solution (not which) one.
Since then, I have had a somewhat working implementation pushed (to openrepos.net) that another community member helpe by creating a GUI for (also published on openrepos.net).
Now, Prey have moved on from the initial bash client, to this version based on nodejs.
I have then crosscompiled nodejs to Jolla phone, and have (as said) this new version also partly working (can track phone location and a bare HW information).
To answer your question. Jolla have their store, yes. They also support Android - somwhat limited, Android does not fully support all HW access of the device.
So, while there is the Jolla store. There really are no core functionality to enable tracking of a stolen device available. At least native to the O/S (Sailfish OS, based on MER).
This is why I am working on this, to create a native solution for Jolla phone (and the upcoming tablet).
While I could temporarily change /etc/mer-release and fool a successfull registration of the device. This is not the way to go ;)

**Comment by lemavri** [comment]
It's great to know you're working on using Prey as a native anti-theft solution, we really appreciate it. I'll forward the request to our web panel developers and let you know as soon as the support for Mer has been added.

**Comment by nieldk** [comment]
Thanks. I (and I am sure many more) appreciate that.

**Comment by fanuneza** [comment]
@lemavri: We need to manage this better. There's no use in having to add each distro as they're reported.

Anything not listed should just be saved as "Linux." I can't see any problem with this approach. What do you think, @michelson?

**Comment by lemavri** [comment]
@fanuneza I agree on a more advanced and automatic way of handling this, but I think this should be discussed in the proper repo.

**Comment by michelson** [comment]
Hola @fanuneza 

This issue is scheduled to be fixed tomorrow, and is at the top of the queue :)

best

**Comment by fanuneza** [comment]
That's great news! Thanks, @michelson.

@lemavri: Absolutely. I just wanted @nieldk to know the status of the problem, and that's beyond Mer and Jolla :)

**Comment by nieldk** [comment]
Thanks all of You.
This is indeed great news.

I can say one member of our community forum for Maemo and SailfishOS
already had two devices stolen..... If he had ony had this solution, I
believe he would have had a much better time :)

Best Regards
Niel

**Comment by lemavri** [comment]
@nieldk, this was fixed a couple of minutes ago. Could you please verify if it's working and let us know how it goes? Thanks in advance!

**Comment by nieldk** [comment]
Super.
I will do some testing the next days.

Thanks once more guys

Niel

**Comment by nieldk** [comment]
Just wanted to let you know.
First tests going well.
Device registers.
Service starts
location working
Report when missing sends: location, hw info, network info (ip and wifi)

Next steps

Packaging

Then make alerts, screenshots, camera - not necessarily in that order :)

Thanks again guys

/Niel

**Comment by explitit** [comment]
Please Add new Sailfish Versions to supported OS list:

https://github.com/prey/prey-node-client/issues/224

**Comment by javo** [comment]
Hello @explitit,
We just have added Sailfish to the list of the supported OS's. Could you please verify if it's working properly and let us know how it goes? Thanks!

**Comment by explitit** [comment]
Thanks, it works on the 
Jolla Tablet JT-1501 with 
Sailfish OS 2.0.2.48 (i486)
now, but not on
Fairphone 2 with
Sailfish 2.0.2.48 (armv7hl)
I get the same
Invalid os: does not exist.
Maybe you need additional information?

**Comment by explitit** [comment]
lsb_release -ri gives me that:

Distributor ID: #Thisfileiscopiedashw-release(analogoustoos-release)
Release:        n/a
[root@Sailfish nemo]#

**Comment by explitit** [comment]
lsb_release (without -ri) gives me that:

LSB Version:    :core-3.1-arm:core-3.1-noarch:core-3.2-arm:core-3.2-noarch:core-4.0-arm:core-4.0-noarch:desktop-3.1-arm:desktop-3.1-noar
ch:desktop-3.2-arm:desktop-3.2-noarch:desktop-4.0-arm:desktop-4.0-noarch
[root@Sailfish nemo]#

**Comment by javo** [comment]
@explitit, could you run the same command in your Jolla Tablet too? 
I believe that you're not able to install Prey in your device because that OS it's a modified version from the original and in order to achieve the installation you could directly modify the Kernel or I could parse this step in the client specially for this case, but I have to review this in more detail.

**Comment by explitit** [comment]
Hm strange. This is the output from the Jolla Tablet:

lsb_release -ri
Distributor ID: #Thisfileiscopiedashw-release(analogoustoos-release)
Release:        n/a
[root@Sailfish nemo]# lsb_release
LSB Version:    :core-3.1-ia32:core-3.1-noarch:core-3.2-ia32:core-3.2-noarch:core-4.0-ia32:core-4.0-noarch:desktop-3.1-ia32:des
ktop-3.1-noarch:desktop-3.2-ia32:desktop-3.2-noarch:desktop-4.0-ia32:desktop-4.0-noarch
[root@Sailfish nemo]#


looks the same way.
SailfishOS on the Fairphone 2 is not very modified version.
Only the Hardware Adaptation is different, but all release dependig settings should be the same.
unfortunately, i don't have the jolla C / intex Aquafish at the moment, but i can ask the guys on the talk.maemo.org forum to test ist on Jolla C.

**Comment by explitit** [comment]
Ok. now i tested it again. i removed the Jolla Tablet from the prey add tryed to add it again from the comman line.
And it didn't work!
it worked the first time because i tryed to add the device with the android app!
Adding a device from the command line doesn't work on tablet and on phone!

**Comment by explitit** [comment]
Any news javo?

Thanks

**Comment by javo** [comment]
Hey @explitit 
Sorry, not yet. I'll let you know as soon as we got something.

**Comment by explitit** [comment]
Thanks for the Info, javo. I will wait. Just say, if i can help you
anyhow....

Thanks

-- 
Kind regards / Mit freundlichen Grüßen
Pawel Radomychelski
ExPLIT IT Solutions
