### ISSUE TITLE
Devices don't report location; can't find access points even though Wi-Fi is on

### ISSUE THREAD

**Issue by fanuneza** [prey/prey-node-client#95]
## Problem

Some devices, including but not limited to Microsoft Surface Pro 3 tablets, can't report a location with the new Prey client. Bash client 0.6.4 reports fine. These are the log errors:

    error Mon, 19 Jan 2015 14:46:00 GMT [reports] Unable to get location: No access points found.
    error Mon, 19 Jan 2015 14:46:00 GMT [reports] Unable to get access_points_list: No access points found.
    error Mon, 19 Jan 2015 14:46:00 GMT [reports] Unable to get active_access_point: No access points found.

## How it was detected

User feedback.

## Suggestion

Find out what's wrong. Fix the access point problem when Wi-Fi is indeed enabled.

## References

- https://help.preyproject.com/topics/unknown-location-for-surface-pro-3-it-s-right-next-to-me
- https://secure.helpscout.net/conversation/77611814/16387/

**Comment by camilaburgos** [comment]
The log file of a OS X user is showing up the same issue.

- https://secure.helpscout.net/conversation/74887296/15430/

**Comment by fanuneza** [comment]
I think I found a pattern after a long time troubleshooting with users. The problem seems to be invalid characters on the nearby SSIDs. For example, when running `netsh wlan show all` you can see characters in the form of �.

Here are some references:

- https://secure.helpscout.net/conversation/87114250/19757/
- https://secure.helpscout.net/conversation/82197228/17862/

**Comment by lemavri** [comment]
Fixed in v1.4.1
