### ISSUE TITLE
Can't get device location

### ISSUE THREAD

**Issue by carlosperalta88** [prey/prey-node-client#99]
Client 1.3.7 can't get device location.

The log:

    info Wed, 11 Mar 2015 20:10:53 GMT [triggers] Watching: connection, network, power
    info Wed, 11 Mar 2015 20:10:53 GMT [actions] Starting trigger: connection
    info Wed, 11 Mar 2015 20:10:53 GMT [actions] Running: connection
    info Wed, 11 Mar 2015 20:10:53 GMT [actions] Starting trigger: network
    info Wed, 11 Mar 2015 20:10:53 GMT [actions] Starting trigger: power
    info Wed, 11 Mar 2015 20:10:53 GMT [actions] Running: network
    info Wed, 11 Mar 2015 20:10:53 GMT [actions] Running: power
    notice Wed, 11 Mar 2015 20:10:53 GMT [control-panel] Checking for existing port mappings...
    info Wed, 11 Mar 2015 20:10:53 GMT Plugin loaded: control-panel
    info Wed, 11 Mar 2015 20:10:53 GMT 1 plugins loaded with 0 errors.
    info Wed, 11 Mar 2015 20:10:53 GMT Initialized.
    notice Wed, 11 Mar 2015 20:10:54 GMT [control-panel] Updating value of scan_hardware to true
    info Wed, 11 Mar 2015 20:10:54 GMT [reports] Gathering specs report.
    error Wed, 11 Mar 2015 20:10:54 GMT [reports] Unable to get storage_devices_list: TODO!
    info Wed, 11 Mar 2015 20:10:54 GMT [reports] Report gathered: specs
    info Wed, 11 Mar 2015 20:10:54 GMT [reports] Gathering status report.
    info Wed, 11 Mar 2015 20:10:56 GMT [reports] Report gathered: status
    info Wed, 11 Mar 2015 20:10:56 GMT [control-panel] Posting data
    info Wed, 11 Mar 2015 20:10:57 GMT [control-panel] Got 200 response: OK
    info Wed, 11 Mar 2015 20:10:58 GMT [control-panel] No previously mapped ports found.
    info Wed, 11 Mar 2015 20:10:58 GMT [control-panel] Attempting to map external port 30329
    error Wed, 11 Mar 2015 20:11:35 GMT [control-panel] Unable to map port: Could not locate gateway on time.
    info Wed, 11 Mar 2015 20:11:35 GMT [control-panel] Queuing check-ins every 0.5 minutes.
    warn Wed, 11 Mar 2015 20:12:06 GMT [control-panel] Got 2 commands.
    info Wed, 11 Mar 2015 20:12:06 GMT [actions] Starting action: alarm
    info Wed, 11 Mar 2015 20:12:06 GMT [control-panel] Posting response
    info Wed, 11 Mar 2015 20:12:06 GMT [actions] Running: alarm
    info Wed, 11 Mar 2015 20:12:07 GMT [control-panel] Got 200 response: OK
    error Wed, 11 Mar 2015 20:12:10 GMT Error: getaddrinfo ENOTFOUND
    info Wed, 11 Mar 2015 20:12:18 GMT [actions] Stopped: alarm
    info Wed, 11 Mar 2015 20:12:20 GMT [control-panel] Posting response
    info Wed, 11 Mar 2015 20:12:21 GMT [control-panel] Got 200 response: OK
    warn Wed, 11 Mar 2015 20:12:37 GMT [control-panel] Got 1 commands.
    info Wed, 11 Mar 2015 20:12:37 GMT [reports] Gathering stolen report.
    info Wed, 11 Mar 2015 20:12:37 GMT [providers] access_points_list already in progress.
    info Wed, 11 Mar 2015 20:12:37 GMT [reports] Queuing stolen report every 2 minutes.
    error Wed, 11 Mar 2015 20:12:40 GMT [reports] Unable to get location: getaddrinfo ENOTFOUND
    info Wed, 11 Mar 2015 20:12:40 GMT [reports] Report gathered: stolen
    info Wed, 11 Mar 2015 20:12:40 GMT [reports] Gathering status report.
    info Wed, 11 Mar 2015 20:12:43 GMT [reports] Report gathered: status
    info Wed, 11 Mar 2015 20:12:43 GMT [control-panel] Posting report
    info Wed, 11 Mar 2015 20:12:47 GMT [control-panel] Got 200 response: Report saved.

**Comment by fanuneza** [comment]
Also failed for me a while ago. A different error, though.

    warn Wed, 11 Mar 2015 20:46:15 GMT [control-panel] Got 1 commands.
    error Wed, 11 Mar 2015 20:46:17 GMT Error: getaddrinfo EAGAIN

And then it worked, like ten minutes later.

    warn Wed, 11 Mar 2015 20:53:40 GMT [control-panel] Got 1 commands.
    info Wed, 11 Mar 2015 20:53:40 GMT [reports] Gathering status report.
    info Wed, 11 Mar 2015 20:53:41 GMT [reports] Report gathered: status
    info Wed, 11 Mar 2015 20:53:41 GMT [control-panel] Posting data
    info Wed, 11 Mar 2015 20:53:42 GMT [control-panel] Got 200 response: OK

**Comment by lemavri** [comment]
Could not reproduce.
